### ISSUE TITLE
Barriers to entry – tick data

### ISSUE THREAD

**Issue by robertmartin8** [hudson-and-thames/mlfinlab#115]
Hi,

In the documentation, you mention that you purchased tick data. Just wanted to notify you of a couple of free sources that I managed to find back when I was playing around with Advances in Financial Machine Learning. 

1. [Dukascopy](https://www.dukascopy.com/swiss/english/marketwatch/historical/). Offers free historical tick data for some futures, though you do have to register.
2. Most crypto exchanges offer tick data but not historical (see [Binance API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md)). So you'd have to run a script for a few days.

Thought that these might be worth mentioning in the docs. 

Best,
Robert

**Comment by Jackal08** [comment]
Hi @robertmartin8, 

Thanks for your recommendation. I have just added your suggestion to the docs: https://mlfinlab.readthedocs.io/en/latest/getting_started/barriers_to_entry.html

Best regards
Jacques
