### ISSUE TITLE
Package Dependancies

### ISSUE THREAD

**Issue by Jackal08** [hudson-and-thames/mlfinlab#116]
When ```pip install mlfinlab``` it doesn't install the package dependencies. Have a look at the setup.py file to see if I can set it up over there.

**Comment by lionelyoung** [comment]
Have you considered poetry?

https://github.com/python-poetry/poetry

**Comment by Jackal08** [comment]
@lionelyoung, thanks for the link!

**Comment by Jackal08** [comment]
Fixed in this pr: https://github.com/hudson-and-thames/mlfinlab/pull/187
