### ISSUE TITLE
doubts - trade data

### ISSUE THREAD

**Issue by rspadim** [hudson-and-thames/mlfinlab#134]
hi folks

i have some doubts to discuss

here in brazil some high liquidy assets have more than one trade per milissecond, in other words "grouping by time" results multiple lines, since there isn't a "primary key" per trade, how could we use this?

from manual trading i have a rule about "tape reading", market runs by orders instead of trades/ticks we should group by order (time + price) and create order instead of a trade, some examples:

| Time  | Price | Volume |
| ------------- | ------------- |  ------------- | 
| 1.001 | 100 | 5 |
| 1.001 | 105 | 5 |
| 1.002 | 100 | 5 |
| 1.002 | 100 | 15 |
| 1.002 | 100 | 25 |

the first line is a single trade selling (considering 100/105 as bid ask), the second one is a buy, lines 3,4,5 are selling but with same order since it's the same price+time, in other words instead of grouping by ticks, we should rebuild and group by order:

| Time  | Price | Volume |
| ------------- | ------------- |  ------------- | 
| 1.001 | 100 | 5 |
| 1.001 | 105 | 5 |
| 1.002 | 100 | 45=5+15+25 |

i'm reading the full repository to understand if this could help with something, as a futures trader this is very helpfull to know what's the order size of "each player"

**Comment by PanPip** [comment]
@rspadim Thank you for reporting this issue!

We've discussed this issue with @Jackal08 and came to the conclusion that this is more of a data pre-processing detail. Trades can be grouped by time and price (or other characteristics) by the user and then used as an input to the MlFInLab function.

@rspadim Do you agree?

**Comment by rspadim** [comment]
maybe just an example, how to do this right

**Comment by PanPip** [comment]
@rspadim if I understood your idea correctly, than this pre-processing step should do the job:

`new_dataset = old_dataset.groupby(['Time','Price']).sum()`
