### ISSUE TITLE
Pass dataframe as input in Standard Bars

### ISSUE THREAD

**Issue by gchamperi** [hudson-and-thames/mlfinlab#139]
I would like to use mlfinlab package to calculate volume/dollar bars and passthe data directly as dataframe and not read them through csv files. I buy your point that historical data might be way too large for memory to handle but it should be up to the user of the package to decide if he/she prefers dataframes over csv files. Neverthelsess, even when using df you could still pass data in batches as you do with the data from csv or just add a comment/warning.

**Comment by globophobe** [comment]
Likewise, the user could also set an inappropriate batch size, and run out of RAM regardless.

Allowing input by data frame seems really easy to implement.

Pull request incoming.

**Comment by proskurin** [comment]
Hi, @gchamperi, @globophobe 
We will add this feature in our next release, which will be quite soon. Stay tuned!
