### ISSUE TITLE
Is it possible to get dollar bar and volume bar based on 1Min ohlc history data?

### ISSUE THREAD

**Issue by coolsnake** [hudson-and-thames/mlfinlab#142]
Some times, we may not get the tick data, but it is easy to download 1min history data with open, high,low,close, volume and amount. 
What I am thinking is to geneate dollar bar and volume bar based on 1Min ohlc history data instead of tick data?

Thanks.

**Comment by globophobe** [comment]
The answer is to try it and find out.

**Comment by Jackal08** [comment]
Hi @coolsnake,

I would argue that if you're going to go to the effort to implement the volume clock based methods then you should make use of high-quality tick data. If you start your research with questionable data then it compromises the quality of your research. 

Many people focus too heavily on these data structures. I think they are great and the imbalance bars have many interesting properties but most of the other techniques still work without applying a volume clock. 

You may find that your statistical properties are still boosted by using dollar bars via minute by minute data.

**Comment by coolsnake** [comment]
Hi @Jackal08 

Thank you for your reply.

The reason I want to use volume clock is that I am trading forex via MT4/MT5 platform. It is difficult to get forex tick data. Even for the 1min data, there is no "dollar" and no real "volume", because the "volume" is quotation changes in one minute. I want to make use of the fake "volume" to generate "volume" bar, then I can do further test.

I hope the package could provide us a new method to generate "dollar" bar or "volume" bar from 1min data instead of tick data.

Thanks.

**Comment by proskurin** [comment]
@coolsnake 
There is no need in special method in this case. Simply apply get_volume_bars on date_time, close, volume from your minute data

**Comment by coolsnake** [comment]
@proskurin If I call get_volume_bars directly on date_time, close, volume, it may omit the HIGH and LOW information of the 1Min bar while tick data doesn't have this kind of problem.
