### ISSUE TITLE
get_time_bars method

### ISSUE THREAD

**Issue by gahobbsau** [hudson-and-thames/mlfinlab#150]
mlfinlab seems to lack a method that would generate time bars from tick data.
- I get that it is probably a trivial df.resample but including such a method would seem to make sense for completion of the library and for analyses.
- Including a get_time_bars method in standard_data_structures would also provide for a consistent output, rather than each using our own methods.

For example, the Research repo at Chapter 2: Getting Started includes a cell that reads the included time_bars csv file and then uses the data in its comparisons and analyses.

**Comment by proskurin** [comment]
Good point, @gahobbsau. We will add this method in our release, which is expected by the end of November
