### ISSUE TITLE
questions about feature_pca_analysis

### ISSUE THREAD

**Issue by motomoto1225** [hudson-and-thames/mlfinlab#151]
I have some questions about 'ml.feature_importance.feature_pca_analysis'.

What is the meaning of repeated_importance_array and all_eigen_values?
I can read the formulas, but I don't know what they mean, nor do I understand their relationship.
Could you explain it briefly or suggest some resources, please?

Thanks a lot.

**Comment by proskurin** [comment]
Hi, @motomoto1225  thank you for your question!

The idea behind PCA analysis is next: eigenvalues are proxy of feature importance in the principal component analysis. If the correlation between eigenvalues and feature importance values is high it means that the pattern was defined by both supervised and unsupervised algorithms. 
As we have several components, for each component feature has the corresponding eigenvalue. To calculate correlation we need arrays of equal length, that is why we repeat feature importance for each component. Let's take a toy example:

3 features: A, B, C with importances 0.3, 0.5, 0.2
PCA analysis yields 3 components with corresponding eigenvalues:
Component 1: 0.1 0.2 0.1
Component 2: 0.3 0.6 0.1
Component 3: 0.3 0.3 0.4

To get correlations we construct 2 arrays:
[0.1 0.2 0.1 0.3 0.6 0.1 0.3 0.3 0.4] and repeated importances [0.3 0.5 0.2 0.3 0.5 0.2 0.3 0.5 0.2] and get correlation between those two.

**Comment by motomoto1225** [comment]
Hi,@proskurin Thank you for your answer!
I wonder if the absolute value of all_eigen_values makes more sense?
I mean pearsonr(all_eigen_values.abs(), repeated_importance_array).

**Comment by proskurin** [comment]
@motomoto1225 that's a very good point. Totally agree with you, we will solve this issue in November-December release. Stay tuned, lots of other features to be added!
