### ISSUE TITLE
data structures get_*_bar different input than csv file

### ISSUE THREAD

**Issue by flamby** [hudson-and-thames/mlfinlab#157]
Hi,

Is it planned to have all those nice data structures methods accepting a dataframe input instead of csv file path? 
It would ease the integration with third-party libs like cryptostore or any libs outputing dataframes from live data.

Right now, it's annoying to have to outputing temporary csv from these live sources on which we get a dataframe from.

Thanks and keep the good work!

**Comment by proskurin** [comment]
Hi, @flamby!
Yeah, one of our PR implements input as a data frame. It will be in our next release (end of November)

**Comment by proskurin** [comment]
We've also added time bars implementation

**Comment by flamby** [comment]
Hi @proskurin 

Great! Closing then ;-)
