### ISSUE TITLE
Performance of SequentiallyBootstrappedBaggingClassifier

### ISSUE THREAD

**Issue by Phibog** [hudson-and-thames/mlfinlab#158]
Hey,

First of all, thanks for this great package.

I'm currently trying the SequentiallyBootstrappedBaggingClassifier with the following code:
```python
rf = RandomForestClassifier(
n_estimators=1,
max_depth=5,
random_state=42,
class_weight='balanced',
min_weight_fraction_leaf=0.05
)

clf = SequentiallyBootstrappedBaggingClassifier(
samples_info_sets=samples_info_sets,
price_bars=price_bars_trim,
base_estimator=rf,
random_state=42,
max_features=4,
max_samples=avg_uniqueness.tW.mean(),
n_estimators=100,
bootstrap_features=True,
n_jobs=20,
verbose=5
)
```
with ~5000 training samples and the training time is > 2h on an aws m4.16xlarge instance. Any ideas of what could be slowing everything down so much? Maybe that many parallell processes creates too much overhead in this setup?

**Comment by proskurin** [comment]
Hi, @Phibog! Thank you for your attention! The process of Sequential Bootstrapping is  exteremely difficult computationally , so it is not strange that it takes a while for a model to train. Try to increase number of cores

**Comment by proskurin** [comment]
And set bootstrap = False in rf, because SequentiallyBootstrappedBaggingClassifier already has bootstrapping

**Comment by Phibog** [comment]
> Try to increase number of cores

Alright, thanks for the advice!

> And set bootstrap = False in rf, because SequentiallyBootstrappedBaggingClassifier already has bootstrapping

Oh, of course. My mistake...

**Comment by proskurin** [comment]
@Phibog welcome!
