### ISSUE TITLE
Cannot use z_score_filter

### ISSUE THREAD

**Issue by geofffoster** [hudson-and-thames/mlfinlab#159]
**Describe the bug**
I cannot use the z_score_filter with the latest release of mlfinlab
**To Reproduce**
import inspect
from mlfinlab.filters import cusum_filter
print (inspect.getmodule(cusum_filter))

  ->  <module 'mlfinlab.filters.filters' from '/home/geoff/anaconda3/envs/yahoo/lib/python3.6/site- 
    packages/mlfinlab/filters/filters.py'>

from mlfinlab.filters import z_score_filter
 ->    ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-f2fc5f1400fc> in <module>
----> 1 from mlfinlab.filters import z_score_filter

ImportError: cannot import name 'z_score_filter'
--
I've installed from both the pip repository and pip from github and still get the same result

**Expected behavior**
Can import z_score_filter like cusum_filter

**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: Mint linux 18.3
 - Browser chromium - but N/A]
 - Version mlfinlab-0.4.1

**Additional context**

**Comment by proskurin** [comment]
Hi @geofffoster,
Thanks for your attention to mlfinlab. It is our fault, we didn't add z-score filter to __init__.py, we will fix that in our next release soon

**Comment by geofffoster** [comment]
thanks - I should have realised that as well - thanks for the fast attention
