### ISSUE TITLE
how to speed up seq_bootstrap

### ISSUE THREAD

**Issue by motomoto1225** [hudson-and-thames/mlfinlab#164]
phi = ml.sampling.seq_bootstrap(ind_mat) is too slow.
For a ind_mat of size 100,000*10,000, it takes hours to work out.
Is there any way to speed it up?
Thanks a lot.

**Comment by proskurin** [comment]
Hi, @motomoto1225 
That's totally true, the complexity structure of seq_bootstrap is O(n^2). We've got a massive performance increase comparing to the book implementation, but it is still slow on very big data sets. You can try optimize algorithm complexity, or try to Cythonise that.
