### ISSUE TITLE
FR: reverse order bar generation ; because data_structures {tick|volume|dollar} last bar is incomplete, which is a problem for inference

### ISSUE THREAD

**Issue by flamby** [hudson-and-thames/mlfinlab#166]
Hi,

I'm using the `data_structures/alex` branch, and realized that the last bar is incomplete, in the sense that for instance, for tick bars with threshold=1000, the last bar's volume is not equal to the volume sum computed manually like so: `df[-1000:].agg({"volume":"sum"})` whereas the first bar's volume is equal to `df[0:1000].agg({"volume":"sum"})`, despite the cum_ticks column value is 1000.

The consequence for machine learning inference will be huge I think, since the last bar won't be similar in term of information to the ones used during training.

The code I used to confirm that:
```python
threshold = 1000
df = pd.read_parquet("data/trades.parquet")
print("First bar's volume computed manually")
print(df.iloc[0:threshold].agg({"volume":"sum"}))
>>>volume    22462.836376
>>>dtype: float64
print("Last bar's volume computed manually")
print(df.iloc[-threshold:].agg({"volume":"sum"}))
>>>volume    268.416395
>>>dtype: float64

custom_ohlc = standard_data_structures.get_tick_bars(df, threshold=threshold, batch_size=1000000,verbose=False)
print("First bar")
print(custom_ohlc.head(1))
>>>            date_time      open      high       low     close        volume  cum_buy_volume  cum_ticks  cum_dollar_value
>>>0 2017-01-01 15:52:52  0.008331  0.008921  0.008331  0.008514  22462.836376    12329.926786       1000        194.043203

print("Last bar")
print(custom_ohlc.tail(1))
>>>                       date_time      open      high       low     close      volume  cum_buy_volume  cum_ticks  cum_dollar_value
>>>15639 2019-12-22 17:48:10.335999  0.017935  0.017935  0.017784  0.017784  210.383762       19.849333       1000          3.749764
```

Last bar's volume computed using `get_tick_bars`should be 268.416395 whereas it is 210.383762, indicating that less than 1000 trades where used for the last bar, **which can be a very random number I guess**, from 1 to 999 trades in my example above, leading to potentially a bar with very low volume.

So the feature request is simple: having an option to those _`get_*_bars`_ function to generate the bar in reverse order, so that the last bar is correct from an information standpoint, and the first bar is not, which is not a problem since we can get rid of it, whether it is training or inference.
I even think that this new behaviour should be the default one, but there might be use cases I did not think about.

Of course I could generate the data manually for inference, but since my feature engineering requires hundreds of bars to `predict` the Target of the last one, I prefer relying on those _`get_*_bars`_  functions for inference data preparation, particularly if using imbalanced bars which are more complex.

What do you think? Does it make sense?

Thanks and keep the good work!

**Comment by proskurin** [comment]
Hi, @flamby. Thank you for your attention to mlfinlab.
There is nothing bad that some trades are not used in the latest bar. The nature of the tick/volume/dollar bar generation is sequential. Furthermore, I can't see any applications of reverse order bar generation, because in this case, you start to suffer from look-ahead bias which is extremely undesirable in algorithmic trading.

**Comment by flamby** [comment]
Hi @proskurin 

Sorry, I have been vague in my fix suggestion.
By reverse order, I don't mean building one bar using ticks in reverse order per se, but build the last bar (let's call it _**b**_) using the last 1000 ticks (in time order), then proceed with the _**b-1**_, and so on. So no lookahead bias.

But a more simpler way would just be to keep it like it is now, but starting with a multiple of the thresholds. That way, the last bar would be complete in the sense that I expressed.

> There is nothing bad that some trades are not used in the latest bar. 

With the current algorithm, if the last bar by any chance is built using only 10 ticks whereas we ask for a threshold of 1000, I do think it's a problem. I don't see how a ML algorithm could get significant information from it from a `volume` and `cum_buy_volume` perspective.

Thanks

**Comment by proskurin** [comment]
The algorithm is implemented is such a way that bar won't be generated until threshold condition is met. So it is not possible to have a bar with num_ticks for example 10 when threshold is 1000

**Comment by flamby** [comment]
> The algorithm is implemented is such a way that bar won't be generated until threshold condition is met. So it is not possible to have a bar with num_ticks for example 10 when threshold is 1000

So why am I having different volume values for my last bar then? (first post example where I compare manually computed with `get_tick_bars`)
Can you try to reproduce my code?

**Comment by proskurin** [comment]
As I can see from your example, the last bar has 1000 ticks which is correct

**Comment by flamby** [comment]
The point is the volume value discrepancy.

**Comment by proskurin** [comment]
Sure, because if you use [-threshold] means that all ticks till the latest one are used, however latest tick bar was formed at point of time before the latest tick in your data set. That is why volume as different.
Let's have a toy example. Let's say, you have 1000 ticks. The sum of volumes of latest 3 ticks (998, 999, 1000) is 200. However, if you generate tick bars with threshold equal to 3, you latest bar with be generated on tick number 998, so volume inside of this bar will be different.

**Comment by flamby** [comment]
I see. My bad. Sorry for that.

Regarding the fact that the algorithm simply drops the last ticks, from a trading perspective, that could be problematic if latest ticks prices drift significantly, would you consider my suggestion of starting the bars creation with a multiple of the threshold then?

**Comment by proskurin** [comment]
The idea of package is to be as close as possible to 'Advances if Financial Machine Learning' book, so this modification will change the behavior of original algorithm and can mislead users

**Comment by flamby** [comment]
I understand. If by any chance I come up with an implementation, would you consider a pull request integration that add it as a non default option? (christmas spirit ;-)

**Comment by Jackal08** [comment]
@flamby, for me it is very important to understand the underlying literature. We use volume or dollars as a proxy for information. The idea is that if there is a volume spike then information has entered the system.

If you implement your reverse logic then this mechanism breaks down. The reason that ticks get dropped in the last bucket is because have havent received the signal to sample the data. Which is inline with the literature.

I dont see a particular problem with that, however if you elaborate then I can respond to specific point.

**Comment by Jackal08** [comment]
> I see. My bad. Sorry for that.
> 
> Regarding the fact that the algorithm simply drops the last ticks, from a trading perspective, that could be problematic if latest ticks prices drift significantly, would you consider my suggestion of starting the bars creation with a multiple of the threshold then?

The implementation is built for a research environment and not for a live data feed. It is under those conditions which I believe the implementation will provide the correct sampling.

If you are using this on live data then the ticks being dropped will be a problem but the expectation is that user will need to build a new implementation for a live data feed.

**Comment by rspadim** [comment]
I only see this usefull when you have to oversample the dataset, resanpling with differents tick starts/ends on the sabe dataset

**Comment by proskurin** [comment]
Yeah, however this logic is valid only for tick bars. It won’t work for volume/dollar

**Comment by rspadim** [comment]
It’s something that can be executed outside of the lib

**Comment by flamby** [comment]
Hi @proskurin @Jackal08 @rspadim 

I came up with this implementation below. At least, it has no impact on normal tick bar creation behaviour and is very little invasive. Tell me if you agree for a pull request, alter it, or want to push it yourself.

I understand the research-only direction, but I'm afraid more and more like me will want to use your lib for live or paper-trading. In a sense, it's the real validation of research to pass it live data, don't you think ;-) and switching to another lib for live trading leads inevitably to fear of bug or differences of implementation, thus, not reproducing research accurately.

```diff
diff -urN -x '*.pyc' b/mlfinlab/mlfinlab/data_structures/base_bars.py mlfinlab/mlfinlab/data_structures/base_bars.py
--- b/mlfinlab/mlfinlab/data_structures/base_bars.py    2019-12-24 22:32:03.654588745 +0100
+++ mlfinlab/mlfinlab/data_structures/base_bars.py  2019-12-25 15:33:19.427715025 +0100
@@ -34,7 +34,7 @@
     they are included here so as to avoid a complicated nested class structure.
     """

-    def __init__(self, file_path_or_df: Tuple[str, pd.DataFrame], metric: str, batch_size: int = 2e7):
+    def __init__(self, file_path_or_df: Tuple[str, pd.DataFrame], metric: str, batch_size: int = 2e7, live: bool = False, threshold: int = None):
         """
         Constructor

@@ -42,14 +42,27 @@
                                 raw tick data  in the format[date_time, price, volume]
         :param metric: (str) type of imbalance bar to create. Example: dollar_imbalance.
         :param batch_size: (int) Number of rows to read in from the csv, per batch.
+        :param live: (bool) Make sure last ticks are part of the last bar, for live trading
+        :param threshold: (Int) Tick threshold
         """

+        self.threshold = threshold
+
         if isinstance(file_path_or_df, str):
             self.generator_object = pd.read_csv(file_path_or_df, chunksize=batch_size, parse_dates=[0])
             # Read in the first row & assert format
             first_row = pd.read_csv(file_path_or_df, nrows=1)
             self._assert_csv(first_row)
         elif isinstance(file_path_or_df, pd.DataFrame):
+            if live:
+                print("*** Dataframe changes for Live Trading ***")
+                print(f"old shape: {file_path_or_df.shape}")
+                # to make sure latest ticks are part of last bar, we get rid of first ticks
+                # not part of a multiple of threshold from a bar perspective
+                rows = file_path_or_df.shape[0]
+                start = rows % threshold
+                file_path_or_df = file_path_or_df.iloc[start:]
+                print(f"new shape: {file_path_or_df.shape}")
             self.generator_object = _crop_data_frame_in_batches(file_path_or_df, batch_size)
         else:
             raise ValueError('file_path_or_df is neither string(path to a csv file) nor pd.DataFrame')
diff -urN -x '*.pyc' b/mlfinlab/mlfinlab/data_structures/standard_data_structures.py mlfinlab/mlfinlab/data_structures/standard_data_structures.py
--- b/mlfinlab/mlfinlab/data_structures/standard_data_structures.py 2019-12-24 22:32:03.654588745 +0100
+++ mlfinlab/mlfinlab/data_structures/standard_data_structures.py   2019-12-25 15:33:01.587767928 +0100
@@ -34,9 +34,9 @@
     """

     def __init__(self, file_path_or_df: Tuple[str, pd.DataFrame], metric: str, threshold: int = 50000,
-                 batch_size: int = 20000000):
+            batch_size: int = 20000000, live: bool = False):

-        BaseBars.__init__(self, file_path_or_df, metric, batch_size)
+        BaseBars.__init__(self, file_path_or_df, metric, batch_size, live=live, threshold=threshold)

         # Threshold at which to sample
         self.threshold = threshold
@@ -59,7 +59,6 @@

         # Iterate over rows
         list_bars = []
-
         for row in data.values:
             # Set variables
             date_time = row[0]
@@ -139,7 +138,7 @@


 def get_tick_bars(file_path_or_df: Tuple[str, pd.DataFrame], threshold: float = 70000000, batch_size: int = 20000000,
-                  verbose: bool = True, to_csv: bool = False, output_path: str = None):
+        verbose: bool = True, to_csv: bool = False, output_path: str = None, live: bool =False):
     """
     Creates the tick bars: date_time, open, high, low, close, volume, cum_buy_volume, cum_ticks, cum_dollar_value.

@@ -149,9 +148,10 @@
     :param verbose: (bool) Print out batch numbers (True or False)
     :param to_csv: (bool) Save bars to csv after every batch run (True or False)
     :param output_path: (str) Path to csv file, if to_csv is True
+    :param live: (bool) Make sure last ticks are part of the last bar, for live trading
     :return: (pd.DataFrame) Dataframe of volume bars
     """
     bars = StandardBars(file_path_or_df=file_path_or_df, metric='cum_ticks',
-                        threshold=threshold, batch_size=batch_size)
+                        threshold=threshold, batch_size=batch_size, live=live)
     tick_bars = bars.batch_run(verbose=verbose, to_csv=to_csv, output_path=output_path)
     return tick_bars
```
I tested it with several tick threshold, and it seems to do the job.

Thanks!

**Comment by rspadim** [comment]
I don’t see why the last bar not complete is a problem.
You can “solve this” at model including a 0/1 variable reporting if bar is complete, the most important variable can’t be this variable. Being the most important variable indicate a bad model for sure or some kind of look ahead or overfitting

About realtime i see as an improvement, we have a historical database and we want to include/remove/change a specific tick, the realtime lib should execute this function fast, and call all indicator functions and after this report that everything is ok

A Next step should be run this in a buck of trades instead of one by one

That’s what a realtime lib should do

**Comment by rspadim** [comment]
A realtime lib should have something like

Init
New tick
Deinit

Where newtick function should be called by a state machine running the marketdata
In the same framework we should have a “create indicator”/“remove indicator” to include others indicators without duplicating that run on the same state machine of the marketdata

The next step should be order sending and algorithmic trading plataform

**Comment by Jackal08** [comment]
> Hi @proskurin @Jackal08 @rspadim
> 
> I came up with this implementation below. At least, it has no impact on normal tick bar creation behaviour and is very little invasive. Tell me if you agree for a pull request, alter it, or want to push it yourself.
> 
> I understand the research-only direction, but I'm afraid more and more like me will want to use your lib for live or paper-trading. In a sense, it's the real validation of research to pass it live data, don't you think ;-) and switching to another lib for live trading leads inevitably to fear of bug or differences of implementation, thus, not reproducing research accurately.
> 
> ```diff
> diff -urN -x '*.pyc' b/mlfinlab/mlfinlab/data_structures/base_bars.py mlfinlab/mlfinlab/data_structures/base_bars.py
> --- b/mlfinlab/mlfinlab/data_structures/base_bars.py    2019-12-24 22:32:03.654588745 +0100
> +++ mlfinlab/mlfinlab/data_structures/base_bars.py  2019-12-25 15:33:19.427715025 +0100
> @@ -34,7 +34,7 @@
>      they are included here so as to avoid a complicated nested class structure.
>      """
> 
> -    def __init__(self, file_path_or_df: Tuple[str, pd.DataFrame], metric: str, batch_size: int = 2e7):
> +    def __init__(self, file_path_or_df: Tuple[str, pd.DataFrame], metric: str, batch_size: int = 2e7, live: bool = False, threshold: int = None):
>          """
>          Constructor
> 
> @@ -42,14 +42,27 @@
>                                  raw tick data  in the format[date_time, price, volume]
>          :param metric: (str) type of imbalance bar to create. Example: dollar_imbalance.
>          :param batch_size: (int) Number of rows to read in from the csv, per batch.
> +        :param live: (bool) Make sure last ticks are part of the last bar, for live trading
> +        :param threshold: (Int) Tick threshold
>          """
> 
> +        self.threshold = threshold
> +
>          if isinstance(file_path_or_df, str):
>              self.generator_object = pd.read_csv(file_path_or_df, chunksize=batch_size, parse_dates=[0])
>              # Read in the first row & assert format
>              first_row = pd.read_csv(file_path_or_df, nrows=1)
>              self._assert_csv(first_row)
>          elif isinstance(file_path_or_df, pd.DataFrame):
> +            if live:
> +                print("*** Dataframe changes for Live Trading ***")
> +                print(f"old shape: {file_path_or_df.shape}")
> +                # to make sure latest ticks are part of last bar, we get rid of first ticks
> +                # not part of a multiple of threshold from a bar perspective
> +                rows = file_path_or_df.shape[0]
> +                start = rows % threshold
> +                file_path_or_df = file_path_or_df.iloc[start:]
> +                print(f"new shape: {file_path_or_df.shape}")
>              self.generator_object = _crop_data_frame_in_batches(file_path_or_df, batch_size)
>          else:
>              raise ValueError('file_path_or_df is neither string(path to a csv file) nor pd.DataFrame')
> diff -urN -x '*.pyc' b/mlfinlab/mlfinlab/data_structures/standard_data_structures.py mlfinlab/mlfinlab/data_structures/standard_data_structures.py
> --- b/mlfinlab/mlfinlab/data_structures/standard_data_structures.py 2019-12-24 22:32:03.654588745 +0100
> +++ mlfinlab/mlfinlab/data_structures/standard_data_structures.py   2019-12-25 15:33:01.587767928 +0100
> @@ -34,9 +34,9 @@
>      """
> 
>      def __init__(self, file_path_or_df: Tuple[str, pd.DataFrame], metric: str, threshold: int = 50000,
> -                 batch_size: int = 20000000):
> +            batch_size: int = 20000000, live: bool = False):
> 
> -        BaseBars.__init__(self, file_path_or_df, metric, batch_size)
> +        BaseBars.__init__(self, file_path_or_df, metric, batch_size, live=live, threshold=threshold)
> 
>          # Threshold at which to sample
>          self.threshold = threshold
> @@ -59,7 +59,6 @@
> 
>          # Iterate over rows
>          list_bars = []
> -
>          for row in data.values:
>              # Set variables
>              date_time = row[0]
> @@ -139,7 +138,7 @@
> 
> 
>  def get_tick_bars(file_path_or_df: Tuple[str, pd.DataFrame], threshold: float = 70000000, batch_size: int = 20000000,
> -                  verbose: bool = True, to_csv: bool = False, output_path: str = None):
> +        verbose: bool = True, to_csv: bool = False, output_path: str = None, live: bool =False):
>      """
>      Creates the tick bars: date_time, open, high, low, close, volume, cum_buy_volume, cum_ticks, cum_dollar_value.
> 
> @@ -149,9 +148,10 @@
>      :param verbose: (bool) Print out batch numbers (True or False)
>      :param to_csv: (bool) Save bars to csv after every batch run (True or False)
>      :param output_path: (str) Path to csv file, if to_csv is True
> +    :param live: (bool) Make sure last ticks are part of the last bar, for live trading
>      :return: (pd.DataFrame) Dataframe of volume bars
>      """
>      bars = StandardBars(file_path_or_df=file_path_or_df, metric='cum_ticks',
> -                        threshold=threshold, batch_size=batch_size)
> +                        threshold=threshold, batch_size=batch_size, live=live)
>      tick_bars = bars.batch_run(verbose=verbose, to_csv=to_csv, output_path=output_path)
>      return tick_bars
> ```
> 
> I tested it with several tick threshold, and it seems to do the job.
> 
> Thanks!

Hi @flamby,

Thank you for the contribution. I need to do a major release for the package where we update the data structures code so I am worried that this will be outdated.

I am open to the idea. I need to take the time to investigate this further and analyse the implementation and its intentions under the context of a sampling technique.

My hope is to get to this before I start work again on the 6th.

**Comment by rspadim** [comment]
I think it’s not a good solution, this “repaint” the chart on each new trade
