### ISSUE TITLE
Incorrect date and close price at Time Bars

### ISSUE THREAD

**Issue by ro99** [hudson-and-thames/mlfinlab#173]
**Describe the bug**
While generating time bars we observe that the Bar Generation condition is reached at an unexpected time i.e. during the first entry of the next date, while it is expected that it should reach in the last entry of current date.

**To Reproduce**
1. put a breakpoint on line 65 of time_data_structures.py.
2. call get_time_bars.
3. observe the TimeStamp from **row** entry.

**Expected behavior**
At the moment that the Bar Generation criteria is reached it is expected that the current row would contain information from last line of current date (since close_price = price and date_time = self.timestamp). But the row at this time contains the information from the first line of the next date.

**Screenshots**
The consolidated information (open, low and high) is from 2019-09-10 but the date that is send to _create_bars is from date 2019-09-11 and (close) price 13.63 (instead of 13.52).

<img width="1613" alt="example" src="https://user-images.githubusercontent.com/2497240/73110617-df1eec00-3ee5-11ea-8b78-84f5f363b280.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15

**Additional context**
I have compared the values with know OHLC sources, and observed that the calculated close price does not match, and the date is shifted+1.

**Comment by artem-matiash** [comment]
Hi @ro99 ! Thank you for using mlfinlab in such a detailed manner and for reaching out!
I am the original author of the idea implemented here, so I can fully share intuition behind mentioned code.

> At the moment that the Bar Generation criteria is reached it is expected that the current row would contain information from last line of current date 

That is not the case here as it is impossible to decide on the current tick whether it is the end of the bar or not. So, here we use the next tick to decide whether its bar label equals current bar label. It means that daily timestamp label e.g. 01.05 00:00:00 (mm.dd HH:MM:SS) contains information from 01.04 00:00:00 inclusively and 01.05 00:00:00 exclusively to entirely avoid look-ahead bias. We were discussing the possiblity of implementing label side parameter (right as it is here, or left i.e. 01.04 00:00:00 as in your OHLC sources) and also inclusion/exclusion of right/left bounds, so I would be excited if you could share your thoughts on the relevance of this change.

> (since close_price = price and date_time = self.timestamp).

date_time is a current tick timestamp, while self.timestamp is a bar label, so their equality sign here is not entirely correct.
In case with close_price you are absolutely correct, information of a new bars tick is used by previous bar, it is a bug, thank you for pointing that out, we will correct it ASAP.

Best regards,
Artem

**Comment by Jackal08** [comment]
@artem-matiash is this issue resolved? I see you merged a PR.

**Comment by artem-matiash** [comment]
Bug was fixed and merged into develop.
