### ISSUE TITLE
ReadTheDocs spelling mistake: 

### ISSUE THREAD

**Issue by Jackal08** [hudson-and-thames/mlfinlab#174]
ReadTheDocs spelling mistake: 

`oos_score = ml_cross_val_score(sclf, X_train, y_train, cv_gen=cv_gen, sample_weight=None,
                                     scoring='accuracy').mean()`

It should read clf not sclf in the example. 

[Feature Importance docs](https://mlfinlab.readthedocs.io/en/latest/implementations/feature_importance.html)

**Comment by patronuscode** [comment]
I will fix this issue.

**Comment by proskurin** [comment]
@patronuscode, sorry, I have already fixed that in fingerpints PR as I was editing feature_importance.rst for fingerprints
