### ISSUE TITLE
Questions 9: Hyper-Parameter Tuning

### ISSUE THREAD

**Issue by Jackal08** [hudson-and-thames/mlfinlab#181]
Answer Ch9: Hyper-Parameter Tuning with Cross-Validation (Advances in Financial Machine Learning) questions.

* In jupyter notebook, add to research repo.

**Comment by Jackal08** [comment]
Hi @Harkishan-99, 

Are you currently working on this ticket?

**Comment by Harkishan-99** [comment]
> Hi @Harkishan-99,
> 
> Are you currently working on this ticket?

Yes, I have almost completed the notebook will do the PR in next 2-3 days. (Some documentation and explanations are left).

**Comment by PanPip** [comment]
This issue is closed with [PR #138](https://github.com/hudson-and-thames/research/pull/138) in the research repo.

Thank you @Harkishan-99!
