### ISSUE TITLE
Optimal Number of Clusters (ONC Algorithm)

### ISSUE THREAD

**Issue by cschiri** [hudson-and-thames/mlfinlab#183]
Regards,

I am having problems with the ONC Algorithm. 

Correct me if I am wrong, but all I need to run the ONC is to import my correlation matrix and feed it into the ONC module as follows:

```
# Import Critical Packages and Dependencies

import pandas as pd
import numpy as np
from mlfinlab.clustering import get_onc_clusters

# Import Correlations File produced by running the df.corr() function of Pandas

corr_mat = pd.read_csv("correlations.csv")

# Get Clusters

clusters = get_onc_clusters(corr_mat, repeat=10)
```

When I run the code, it gives me this error:

> TypeError: unsupported operand type(s) for -: 'int' and 'str'

Help!

Everything thing else in the package--excluding the SFI Algorithm for feature importance discovery (too slow) and the PCA algorithm--works well. 

Best
-C.

**Comment by pauli2406** [comment]
Hey, you have to call .corr()
before calling the algorithm. Add the following.

corr_mat = corr_mat.corr()

Also make sure all values of your data frame are numeric

**Comment by proskurin** [comment]
Hi @pauli2406 , @cschiri 
Thank you for you interest ! The input for ONC is a correlation matrix, so @cschiri your input is good, but make sure that your correlation doesn't contain any strings. If you still get an error, you can send me your correlation matrix and I can assist you.

**Comment by cschiri** [comment]
@pauli2406 The matrix that I loaded via the "pd.read_csv" command was indeed created using Pandas "df.corr()" command and saved as a csv file which I loaded in this instance. 

@proskurin The dataset from which the correlation frame was derived had a few binarized variables (-1,0,1). The columns that represent these variables have gaps. Could they be the source of the issues that I am facing?

**Comment by proskurin** [comment]
Yep, it can lead to some problems, in this case your correlation matrix may have NA values. Just check your saved file with correlations for NA values

**Comment by cschiri** [comment]
The problem emanated from two sources:

- There were N/A values in the correlation matrix (@proskurin your suspicion was on point).
- And, some of the correlations that were close to zero, e.g. 0.0003, were--once they were manipulated by the algorithm--resulting in outputs that approached infinity and caused errors! 

Solved by adding an additional layer of data cleansing! The ONC algorithm works!
