### ISSUE TITLE
Failure to update to 0.5.1

### ISSUE THREAD

**Issue by sukioral** [hudson-and-thames/mlfinlab#185]
After I typed the command "pip install mlfinlab --upgrade" in the terminal, the mlfinlab version does not update to 0.5.2 and remains at 0.5.1. May I ask how can I fix the issue? Thanks.

p.s. Currently using anaconda with python 3.7 version.

**Comment by Jackal08** [comment]
Hi @sukioral, 

Well spotted, I just updated the PyPi index. Would you mind to please try again? It should work now. 

Please do let us know if it doesn't.

**Comment by sukioral** [comment]
That's great. It works now. Thank you very much.

**Comment by Jackal08** [comment]
My pleasure.

**Comment by Jackal08** [comment]
If you like the work we do here, please do star the repo and help us spread the news!
