### ISSUE TITLE
Implement Shapley values

### ISSUE THREAD

**Issue by proskurin** [hudson-and-thames/mlfinlab#186]
https://christophm.github.io/interpretable-ml-book/shap.html

**Comment by rspadim** [comment]
I think it’s plug and play, not? What model we want to implement it?

**Comment by Jackal08** [comment]
There is a package for Shapely?

**Comment by rspadim** [comment]
Shapely or shap? https://github.com/slundberg/shap

**Comment by proskurin** [comment]
The package looks great, no need to implement that
