### ISSUE TITLE
Sklearn Future Warning

### ISSUE THREAD

**Issue by Jackal08** [hudson-and-thames/mlfinlab#190]
Update package to be inline with the following:
```
FutureWarning: The sklearn.ensemble.bagging module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
```

**Comment by JamieWalker01** [comment]
I would like to be assigned this.

**Comment by JamieWalker01** [comment]
This is my first contribution, could you tell me which file the code is to be fixed?

**Comment by Jackal08** [comment]
Hi @JamieWalker01, 

Excellent! The first place to look is in the sequential bootsrapped files.

**Comment by JamieWalker01** [comment]
Sorry @Jackal08 , Im not sure what you mean by sequential bootstrapped files, could you explain a bit more?

**Comment by Jackal08** [comment]
I think these are the files: https://github.com/hudson-and-thames/mlfinlab/blob/master/mlfinlab/ensemble/sb_bagging.py

**Comment by Jackal08** [comment]
You will have to double-check for additional sources but I would start there.

**Comment by JamieWalker01** [comment]
It appears the function BaseBagging can not be installed from sklearn.ensemble so is part of the private API in the new version. How would you go about installing it in the code?

**Comment by Jackal08** [comment]
Hi @JamieWalker01, 

Sorry for the delay, it has actually been a big job and this ticket was part of a much bigger ticket on updating all our package dependencies and updating the code to reflect those changes. 

@PanPip has made all of the adjustments and a new version will go out this weekend. 

Feel free to grab some new tickets. 

Best regards
Jacques Joubert
