### ISSUE TITLE
readthedocs - Wrong Fractionally Differentiated Image

### ISSUE THREAD

**Issue by rspadim** [hudson-and-thames/mlfinlab#191]
This [page](https://mlfinlab.readthedocs.io/en/latest/implementations/frac_diff.html) have a wrong [image](https://mlfinlab.readthedocs.io/en/latest/_images/frac_diff_graph.png) example

The fracdiff is a fir filter, and the left side should be np.NaN values, probably the example is using a np.diff() = integer diff

**Comment by Jackal08** [comment]
Fixed in #263
