### ISSUE TITLE
Codependence Module Inputs: Clarification Needed

### ISSUE THREAD

**Issue by cschiri** [hudson-and-thames/mlfinlab#196]
Regards,

I need clarification on one thing:

The angular distance co-dependence module take two inputs, X and Y

`absolute_angular_distance(X, Y)`

Is X the numpy array of all dependent variables, or is it a numpy array of a  single dependent variable? Are the dependent variables tested in one go, or are they tested one by one?

**Comment by rspadim** [comment]
it's a vector

it's not a canonical correlation like metric

**Comment by Jackal08** [comment]
@proskurin, I think we need to adjust the arguments here. Capital letters are usually reserved for a matrix.

**Comment by Jackal08** [comment]
@cschiri if your in a notebook, adding a `?` to a function will bring up the docstrings. 

I can see that for angular_distance:

```Returns angular distance between two vectors. Angular distance is a slight modification of correlation which satisfies metric conditions.```

So x, y are each a vector. So it would be between two variables. The following documentaiton will help: https://mlfinlab.readthedocs.io/en/latest/implementations/codependence.html#correlation-based-metrics

**Comment by cschiri** [comment]
Thank you!
