### ISSUE TITLE
Change triple_barrier_events function to be compatibile with pandas 1.0

### ISSUE THREAD

**Issue by MislavSag** [hudson-and-thames/mlfinlab#197]
**Describe the bug**
I tried to implement triple_barrier_events function. IT returned an error 

> KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

I can overcome the problem if I use pandas reindex function.

**To Reproduce**
Inside triple_barrier_events, this part produces error:
`target = target.loc[t_events]`
produces above error.
Pandas documentation recommend using reindex:
`target = target.reindex(t_events)`

**Desktop (please complete the following information):**
Windows
Pandas 1.0.1

**Comment by rspadim** [comment]
When refering documentation, if possible, include the link to documentation

**Comment by MislavSag** [comment]
@rspadim, link to documentation is in error message:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike

It says:

> Warning
> 
> Starting in 0.21.0, using .loc or [] with a list with one or more missing labels, is deprecated, in favor of .reindex.

So, in the function get evetns this part:
 ```
   # 1) Get target
    target = target.loc[t_events]
    target = target[target > min_ret]  # min_ret

```
according to documentation should be changed to:
```
    # 1) Get target
    target = target.reindex(t_events)
    target = target[target > min_ret]  # min_ret

```
The problem is that first operation produce Nan values (there are CUSUM events dates that are not in daily volume dates because daily_volume has Nan in the begining of the series)

**Comment by Jackal08** [comment]
Hi @MislavSag, 

This error is due to us not having ported the codebase to pandas 1.0.1, if you downgrade to before 1.0.0 then everything will work as expected.

**Comment by Jackal08** [comment]
We have added porting to pandas 1.0.1 to the todo items. :)

**Comment by BlackArbsCEO** [comment]
@Jackal08 

I'm going to make the adjustment to my personal version, but wanted to get clarification on, if there was any reason to keep the NaN by using reindex or if the function should keep only valid keys per the pandas example [link](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-with-list-with-missing-labels-is-deprecated).

Example from their docs below:
```
# current behavior
In [4]: s.loc[[1, 2, 3]]
Passing list-likes to .loc with any non-matching elements will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike

Out[4]:
1    2.0
2    3.0
3    NaN
dtype: float64

#=========================
# reindex

In [101]: s.reindex([1, 2, 3])
Out[101]: 
1    2.0
2    3.0
3    NaN
dtype: float64

#=========================
# intersection

In [102]: labels = [1, 2, 3]

In [103]: s.loc[s.index.intersection(labels)]
Out[103]: 
1    2
2    3
dtype: int64

```

**Comment by Jackal08** [comment]
Hi @MislavSag, 

We have updated all the packages and are doing a version release this weekend. That includes updating all our code to work with the new packages. 

I am going to close this issue but if you had an additional bug fix included or fixes to docstrings, please do reopen it or ping me in Slack. 

Best regards
Jacques

**Comment by MislavSag** [comment]
Hi @Jackal08 ,

that's great news. Can't wait to test new versions.

Best,

Mislav
