### ISSUE TITLE
Improving the processing speed of Entropy Features

### ISSUE THREAD

**Issue by Harkishan-99** [hudson-and-thames/mlfinlab#198]
I recently tried using the Intra-Bar MicroStructural Features using the MicrostructuralFeaturesGenerator class. I found that it takes a very long time to process even on 2-3 month of tick data. Finally, after some exploration of the code behind I came to understand that the entropy feature function excluding Shannon's Entropy function takes the most amount of time.
The entropy features contain one or more for loops and that makes the function very inefficient and difficult to scale it to a larger dataset.

Maybe the codes can be improved (, I am working on it). Or apply multiprocessing. Or use Cython.
Anyway, I encourage the community to work on it.

**Comment by Harkishan-99** [comment]
With some further exploration, I came to know the _match_length function of the konto_entropy has the highest compute time of approx. 13-14 sec with a string message of length 1000. I managed to bring it down to under 3 sec adding a small Cython modification to the match_length function.

`cpdef matchLength(str msg, int i,int n):
    # Maximum matched length+1, with overlap.
    # i>=n & len(msg)>=i+n
    cdef str subS = ''
    cdef int l,j
    cdef str msg0,msg1
    for l in range(n):
        msg1=msg[i:i+l+1]
        for j in range(i-n,i):
            msg0=msg[j:j+l+1]
            if msg1==msg0:
                subS=msg1
                break # search for higher l.
    return len(subS)+1,subS`

**Comment by Jackal08** [comment]
Thanks @Harkishan-99, 

Would you mind to please open a PR for this? If your code works as expected then all the unit tests in their current form should pass.

**Comment by PanPip** [comment]
This issue was fixed by @Gunther-Schulz in PR #311.

It will be merged into `develop` branch with PR #412.
