### ISSUE TITLE
Feature importance example usage docs out-dated

### ISSUE THREAD

**Issue by dodafin** [hudson-and-thames/mlfinlab#199]
Correct me if I'm wrong but the example at the bottom of the page here https://mlfinlab.readthedocs.io/en/latest/implementations/feature_importance.html#mlfinlab.feature_importance.importance.plot_feature_importance is out-dated since the MDI method has since been renamed and scoring functions are passed by-function rather than by-string?

Happy to fix this myself, once I'm done with Ch8 Feature Importance.

*EDIT: Also the file name is duplicated :)

**Comment by proskurin** [comment]
@dodafin you are absolutely right, very good point, need to fix that

**Comment by Jackal08** [comment]
I have just updated the docs but we need to also update the code example in the docs.
