### ISSUE TITLE
Mistakes in the Micro-structural Features Documentation

### ISSUE THREAD

**Issue by Harkishan-99** [hudson-and-thames/mlfinlab#200]
The example that was given at the end of the documentation page [https://mlfinlab.readthedocs.io/en/latest/implementations/microstructural_features.html](url)
has a couple of things not going right.
1) The usage of whole tick dataset to form the quantile mapping will cause look-ahead bias as we are now computing the quantile based future data for a bar. (I have pointed the usage of full dataset)

2) The example takes the DateTime Index of the bars and puts in tick_num_series param of the MicrostructuralFeaturesGenerator class, which is invalid a will output and error. (Highlighted in the below image)
![microstructure mistakes](https://user-images.githubusercontent.com/45006182/74736589-21371580-5279-11ea-8c49-15e1f009f4f9.PNG)

It should have been like.

`tick_num = compressed_bars.tick_num`

**Comment by proskurin** [comment]
Hi, @Harkishan-99 
Thank you very much for your comments! You are absolutely right, we will fix docs bugs in our next release
