### ISSUE TITLE
OAS wrong input

### ISSUE THREAD

**Issue by qchen92** [hudson-and-thames/mlfinlab#203]
**Describe the bug**
in hrp.py, _shrink_covariance function,
the input to oas.fit should be the returns, not the covariance matrix.

**Comment by aditya1702** [comment]
@qchen92 Thanks for bringing this issue to the attention!

**Comment by Jackal08** [comment]
@aditya1702, have we corrected this ticket?

**Comment by aditya1702** [comment]
@Jackal08 Yes, I have done this. Will make a commit for this

**Comment by Jackal08** [comment]
Fixed in this PR: #224
