### ISSUE TITLE
Feature Importance MDA

### ISSUE THREAD

**Issue by stevenvanwinkel** [hudson-and-thames/mlfinlab#207]
I received the following error while running the function importance.feature_importance_mean_decrease_accuracy

**Screenshots**
![image](https://user-images.githubusercontent.com/42768225/75228281-2b44a100-57b0-11ea-97d8-07cb65994518.png)

Is this an error on my side or with the code?

**Comment by Jackal08** [comment]
Its hard to tell. 

* I can see that your using an older version of the package. I would update.
* You have 16 folds, that is a serious amount of folds (too many in my opinion), Try run with 4 folds and see if you get the same error.

**Comment by stevenvanwinkel** [comment]
thanks Jacques for your quick answer. I tried with the newer package and with fewer folds. Same thing unfortunately. I'll try without the sample weights.

**Comment by Jackal08** [comment]
My pleasure. I would be interested to hear what the problem is. I use this feature importance very often and haven't run into problems yet. Maybe we have overlooked something.
