### ISSUE TITLE
Find optimal diff_amt argument in frac_diff_ffd function

### ISSUE THREAD

**Issue by MislavSag** [hudson-and-thames/mlfinlab#211]
**Is your feature request related to a problem? Please describe.**
I was reading today chapter 5 in the book. A have also checked your frac_diff_ffd  function to implement fractional differentiation. Is it possible to find the "optimal" value of diff_amt, where optimal means as low as a possible value of diff_amt that makes times series stationary? I know I can do it on my own by using some kind of optimization method, but maybe you have already implemented this procedure?

**Describe the solution you'd like**
I would like to write a function that automatically finds the lowest value of frac_diff that makes series stationary.

**Describe alternatives you've considered**
I checked notebooks, but they don't try to find optimal value.

**Additional context**
No additional context.

**Comment by Harkishan-99** [comment]
Hi, @MislavSag that is a really good question. In fact, I was on these yesterday. Dr Lopez de Prado has mentioned how to obtain the minimum value of diff_amt in the book. You can also see the implementation in the research [notebook,](https://github.com/hudson-and-thames/research/blob/master/Chapter5/Chapter5_Exercises.ipynb) where the plot_min_ffd has been used. 
What I have done is just modified the plot_min_ffd function and to return the diff_amt value as soon as the p_value drops below 0.05.

**Comment by Jackal08** [comment]
Hi @MislavSag, 

If you have an additional implementation you would like to add to the package. We would certainly welcome your contributions.

**Comment by MislavSag** [comment]
I have change a little bit plot function from notebbok:
```
def min_ffd_plot(unstationary_pdseries):
    """Plot:
    1) correlation bretween first current value and first lag 
    2) 5% pavlaue for ADF test
    3 ) mean of ADF 95% confidence
    
    Arguments:
        unstationary_pdseries {pd.Series} -- pd.Series you want to plot
    """
    out = pd.DataFrame(columns=['adfStat', 'pVal', 'lags', 'nObs', '95% conf', 'corr'])
    for d in np.linspace(0, 1, 11):
        df1 = np.log(unstationary_pdseries).resample('1D').last()  # downcast to daily obs        
        df1.dropna(inplace=True)
        df2 = frac_diff_ffd(df1, diff_amt=d, thresh=0.01).dropna()
        corr = np.corrcoef(df1.loc[df2.index].squeeze(), df2.squeeze())[0, 1]
        df2 = adfuller(df2.squeeze(), maxlag=1, regression='c', autolag=None)
        out.loc[d] = list(df2[:4]) + [df2[4]['5%']] + [corr]  # with critical value
    out[['adfStat', 'corr']].plot(secondary_y='adfStat', figsize=(10, 8))
    plt.axhline(out['95% conf'].mean(), linewidth=1, color='r', linestyle='dotted')
    return
```
I have also make simple function to fin minimum d that makes time series stationary:
```
def min_ffd_value(unstationary_pdseries, pvalue_threshold=0.05):
    """Minimal value of d which makes pandas series stationary.
    
    Arguments:
        unstationary_pdseries {pd.Series} -- Pandas series for which you want to find d.
    
    Keyword Arguments:
        pvalue_threshold {float} -- P value threshold (default: {0.05})
    
    Returns:
        [float] -- Minimum value of d that makes series staionary.
    """
    for d in np.linspace(0, 1, 11):
        df1 = np.log(unstationary_pdseries).resample('1D').last()       
        df1.dropna(inplace=True)
        df2 = frac_diff_ffd(df1, diff_amt=d, thresh=0.01).dropna()
        df2 = adfuller(df2.squeeze(), maxlag=1, regression='c', autolag=None)
        if df2[1] <= pvalue_threshold:
            return d
```
I am not thta familiar with python (comed from R), so you can check if everything is ok.

**Comment by Harkishan-99** [comment]
@MislavSag  Yeah that is correct. You can also control the granularity by changing the value of the number of samples you want to generate with np.linspace.

**Comment by MislavSag** [comment]
Update with d_domain argument
```
def min_ffd_value(unstationary_pdseries, d_domain, pvalue_threshold=0.05):
    """Minimal value of d which makes pandas series stationary.

    Arguments:
        unstationary_pdseries {pd.Series} -- Pandas series for which you want to find d.
        d_domain {np.array} -- sequence of possible values of d.

    Keyword Arguments:
        pvalue_threshold {float} -- P value threshold (default: {0.05})

    Returns:
        [float] -- Minimum value of d that makes series staionary.
    """
    for d in d_domain:
        df1 = np.log(unstationary_pdseries).resample('1D').last()
        df1.dropna(inplace=True)
        df2 = frac_diff_ffd(df1, diff_amt=d, thresh=0.01).dropna()
        df2 = adfuller(df2.squeeze(), maxlag=1, regression='c', autolag=None)
        if df2[1] <= pvalue_threshold:
            return d
```

**Comment by Jackal08** [comment]
Hi @MislavSag, 

Why did we close this ticket? Is this not code that should be added to the package?

**Comment by MislavSag** [comment]
@Jackal08 , sorry, I thought I should close it since I have found a solution that works for me.

Can I help you somehow to add it to the package?

**Comment by proskurin** [comment]
Hi @MislavSag 
Thank you very much for your contribution. The function would be a great addition to the package. Could you please create fork -> create PR to develop branch (add docstrings and tests to pass CI checks)
Thanks,
Alex

**Comment by MislavSag** [comment]
@proskurin , I forked and cloned repo, add function to the fracdiff submodule and add docstrings, just not sure about tests. Where should I write tests?

**Comment by MislavSag** [comment]
I have added a test to tests submodule. I have changed existing test_fracdiff.py test file. But when I run the test I got the error:

> AttributeError: module 'mlfinlab.features.fracdiff' has no attribute 'min_ffd_value'
Can you guess what can be the problem?

This is the first time I am making contributions to other packages, so maybe it si something basic I missed.

**Comment by MislavSag** [comment]
Function is added to the package.
