### ISSUE TITLE
ml_cross_val_score() docu outdated, TypeError for sample weights

### ISSUE THREAD

**Issue by Channaholic** [hudson-and-thames/mlfinlab#249]
Hey,

first of all, thx for this package!

1. 
In the documentation, there is a difference between the parameters in the code example snippet and the parameters described below (**sample_weight** vs **sample_weight_train, sample_weight_score**)

2.
I am not able to use the method with either param version.
I am getting this type error when trying to copy the code from the snippet:

> **TypeError: ml_cross_val_score() got multiple values for argument 'sample_weight'**

When I use the sample_weight_train param as described in the documentation it says that its an unknown argument (my package version is 0.8.0)

To specify: 
I am trying to reproduce [this ](https://github.com/hudson-and-thames/research/blob/master/Chapter4/Trend-Follow-Question-Extended-SB-Cross-Val.ipynb)notebook with a different primary model and am stuck now at the Cross-Validation part

Thx!

**Comment by MislavSag** [comment]
Please provide code. It'd hard to say without reproducing it. `sample_weight` should be pd.Series.

**Comment by Channaholic** [comment]
I am trying to reproduce [this ](https://github.com/hudson-and-thames/research/blob/master/Chapter4/Trend-Follow-Question-Extended-SB-Cross-Val.ipynb) notebook with a different primary model and am stuck now at the Cross-Validation part. So code is the same like cells 42 to 46

**Comment by MislavSag** [comment]
Does it work with the same primary model, if you try to execute notebbok till `sample_weight` part?

**Comment by Channaholic** [comment]
It does not, but I am getting different errors. The first one is **TypeError: 'str' object is not callable** for cell 38 Line 31. When I change the **scoring = scoring** to **'f1'** I get another Error for the same line **TypeError: only integer scalar arrays can be converted to a scalar index**

![image](https://user-images.githubusercontent.com/38936786/78275193-900ebc00-7511-11ea-9633-36c123694f4e.png)

**Comment by MislavSag** [comment]
I also got this error before and I remember I had to change "f1" to `f1` sklearn scorer.

https://scikit-learn.org/stable/modules/model_evaluation.html

**Comment by Channaholic** [comment]
Works now, pls change it in the documenation, Thanks!

**Comment by Jackal08** [comment]
@MislavSag Thanks so much for answering this!

I left this ticket open so that we know to update the docs.

**Comment by Jackal08** [comment]
@PanPip, can we please fix this issue for this weekends version release?

**Comment by PanPip** [comment]
@Jackal08 Fixed issue in the documentation in #383 

We will also need to update the Cross-Validation Notebook. Created a [new issue](https://github.com/hudson-and-thames/research/issues/163) for that.
