### ISSUE TITLE
Add Online Portfolio Selection Algorithms

### ISSUE THREAD

**Issue by Jackal08** [hudson-and-thames/mlfinlab#252]
Inspiration Paper: https://jfds.pm-research.com/content/1/2/78

**Comment by robertmartin8** [comment]
There's a cool library related to this: https://github.com/Marigold/universal-portfolios

But I don't know if it's maintained

**Comment by Jackal08** [comment]
Hi @robertmartin8, 

Thanks for the heads-up, we have been in communication with [Marigold](https://github.com/Marigold/universal-portfolios/issues/28).

**Comment by Jackal08** [comment]
Closing this ticket as @akwon31 is almost finished implementing a full module for these techniques.

**Comment by Chris-Reichelt** [comment]
I look forward to seeing the great work..

**Comment by Jackal08** [comment]
@Chris-Reichelt, we are almost finished. Hopefully a version release in the next week!
