### ISSUE TITLE
Better code for ffd

### ISSUE THREAD

**Issue by cottrell** [hudson-and-thames/mlfinlab#265]
https://github.com/cottrell/fractional-differentiation-time-series

In general, I would suggest most of Prado's code needs rewriting: 

a) don't use pandas if you can help it
b) "clear a path" for numba and then cython.

lru_cache on the weights creation will help those who are calling this on DataFrames as well.

**Comment by Harkishan-99** [comment]
I completely agree with you and if you don't mind I request you to do a PR for the improved code. By the way, you did a great job with the code.

**Comment by cottrell** [comment]
I've started with this for the perf stuff. I'm not sure how active asv is but it appears to be still the main deal for pandas. 

https://github.com/hudson-and-thames/mlfinlab/pull/271

Currently only works in the "existing" mode. See Makefile.

**Comment by PanPip** [comment]
Upon discussing with @Jackal08 decided that this issue can be closed. Moving the whole package away from pandas will depend on the future goals of MlFinLab.

However, PRs with improved code are welcome 😄
