### ISSUE TITLE
Check for timing improvements again this getQuasiDiag method

### ISSUE THREAD

**Issue by cottrell** [hudson-and-thames/mlfinlab#266]
https://github.com/cottrell/hrp/blob/master/hrp/__init__.py#L70

I wrote that before I discovered mlfinlab. Was about 700x on Prado's original, not sure about current mlfinlab version.

**Comment by aditya1702** [comment]
@cottrell Thanks for this link and issue. Although, I have not used de Prado's method due to the speed reasons, I will check it against yours and update the code if your method performs faster

**Comment by Jackal08** [comment]
@aditya1702 is this still an open issue? If not please will you close it.
