### ISSUE TITLE
Dynamic Threshold for Standard Bar Structure

### ISSUE THREAD

**Issue by Harkishan-99** [hudson-and-thames/mlfinlab#269]
As market change over time, the number of shares traded changes significantly. So I think we should make the threshold argument of the standard bar in the data structure to take in both static (int) and dynamic (pd.Series with datetime_index) threshold. This can let the user sample the volume and dollar_volume bars with a dynamic threshold and adapt to the changes in the market. This was also mentioned in the book Adv. in Financial ML (page-28, 2nd paragraph). He advised not to keep the size of the bar constant over time, instead dynamically adjust it as a function of the free-floating market capitalization of a company (in the case of stocks), or the outstanding amount of issued debt (in the case of fixed-income securities).

**Comment by PanPip** [comment]
@Harkishan-99 Thank you for proposing this idea! 😄 

Now functions from **Data Structures/Standard Bar**: `get_dollar_bars,` `get_volume_bars`, `get_tick_bars` allow an input of a dynamic threshold in a form of pd.Series. Furthermore, values in the input pd.Series are needed only when the threshold is changed and not for every observation. (Example is present in the Tip section of the documentation).

Feature added in PR #402
