### ISSUE TITLE
Tail-Sets Label Documentation Bug

### ISSUE THREAD

**Issue by Harkishan-99** [hudson-and-thames/mlfinlab#285]
It was mentioned in the documentation to use `df.lag(1)` as a pandas DataFrame method to make it forward-looking. But neither `pandas.DataFrame` nor `pandas. Series` has the method `lag`. Instead, `.shift(-1)` can be used if the goal is to make the series lag by 1.

**Comment by PanPip** [comment]
@Harkishan-99 Thank you for noticing this bug.

As you've suggested `.shift(-1)` will be used now. This issue is fixed in PR #402.
