### ISSUE TITLE
information leakage issue about 't1' column

### ISSUE THREAD

**Issue by jihobak** [hudson-and-thames/mlfinlab#288]
https://github.com/hudson-and-thames/mlfinlab/blob/7543bd7180eb051415a31b2c4e1cd45ef00d3f18/mlfinlab/labeling/trend_scanning.py#L73

In the code, 't1' indicates the time when absolute of t-value is maximum. But, code in the book, ML for asset managers, 't1' is the timestamp of the farthest observation used to find the most significant trend. So, it's an almost fixed length(t:t+L).

Isn't it cheating to use 't1' as the time when absolute of t-value is maximum?

**Comment by MislavSag** [comment]
@jihobak , Purpose of trend scanning is to construct labels. If you use a fixed time method, you define a label as 1 if return > 0 in the future, vice versa. Trend scanning uses trends instead of fixed points in the future for constructing labels.

**Comment by jihobak** [comment]
@MislavSag Thanks for your comment. Yeah, I understand your point. So, you think the information leakage issue does not matter in terms of making labels?

**Comment by MislavSag** [comment]
I read your comment again. You think t1 should be point where "trend ends". But that would be always t + window size? 

I think it also depends on how do you use t1 latter. In triple barrier t1 is the exit position. Not sure we should have the same interpretation in trend scanning. Actually, that is a good question. What is an exit time in trend scanning. It should probably be endogenously determined.

**Comment by Jackal08** [comment]
Hi @jihobak, 

In this case the forward looking labels is intentional and it is not data leakage. 

@MislavSag I noticed that LdP used t1 to be the max length scanned and I agree with you that having the end of the trend, is a more useful value, at least in the context that I was using it.
