### ISSUE TITLE
duplication of sorted function 

### ISSUE THREAD

**Issue by jihobak** [hudson-and-thames/mlfinlab#289]
https://github.com/hudson-and-thames/mlfinlab/blob/7543bd7180eb051415a31b2c4e1cd45ef00d3f18/mlfinlab/sampling/bootstrapping.py#L34-L38

I think this is a duplication. just twice sorted. Am I mistaken?

Thanks

**Comment by PanPip** [comment]
@jihobak Thank you for reporting this issue!

It's indeed a duplication. This issue is fixed in PR #402.
