### ISSUE TITLE
improve the calculation of daily volatility in util.volatility.get_daily_vol()

### ISSUE THREAD

**Issue by tantants** [hudson-and-thames/mlfinlab#292]
In util.volatility.get_daily_vol(), line 26, I think you didn't take into account the holidays or other non-trading days, I suggest replace line 26 by the following codes:

# all dates in the time series of close prices
dates = sorted(list(set([x.date() for x in close.index])))
# get number of days to the previous trading date
delta_dates = pd.Series()
delta_dates.loc[dates[0]] = datetime.timedelta(days=1)
for i in range(1, len(dates)):
    delta_dates.loc[dates[i]] = dates[i] - dates[i-1]
# previous trading date for each index in the time series of close prices
prev_dt = pd.DatetimeIndex([x-delta_dates.loc[x.date()] for x in close.index])
# get the positions of moving backward for one trading day 
df0 = close.index.searchsorted(prev_dt)

**Comment by boyboi86** [comment]
I think it was discussed previously.

[https://github.com/hudson-and-thames/mlfinlab/issues/87](url)

**Comment by Jackal08** [comment]
Hi @tantants, 

Did issue #87 help answer your question?

Best regards
Jacques

**Comment by PanPip** [comment]
Closing stale issue.
