### ISSUE TITLE
Docstrings: Feature Clustering & Importance

### ISSUE THREAD

**Issue by Jackal08** [hudson-and-thames/mlfinlab#300]
Need to write better docstrings. 

Please do so in a new branch. :)

**Comment by Harkishan-99** [comment]
Sure. Do you have any particular comment on what shall I focus on?

**Comment by Jackal08** [comment]
@Harkishan-99, has this ticket been resolved? Can I close it?

**Comment by Harkishan-99** [comment]
Yes, it was completed.
