### ISSUE TITLE
Replace numba ewma with faster version

### ISSUE THREAD

**Issue by proskurin** [hudson-and-thames/mlfinlab#31]
Numba ewma works very well for small arrays and small windows. However, in imbalance bars implementation windows are usually quite big, that is why we need to optimize ewma code performance

**Comment by jgerardsimcock** [comment]
@proskurin are you suggesting using an alternative library to numba to speed up the fast_ewma [here](https://github.com/hudson-and-thames/mlfinlab/blob/master/mlfinlab/util/fast_ewma.py)? Or do want to just optimize the code in general?

**Comment by proskurin** [comment]
@jgerardsimcock current EWMA version works fast on small window values. However, in imbalance bars window length is usually big, so we need to get a version of EWMA that works fast on big windows
