### ISSUE TITLE
Soften version requirements

### ISSUE THREAD

**Issue by mirca** [hudson-and-thames/mlfinlab#319]
``mlfinlab`` requires "hard" versions of libraries such as ``numpy==1.17.3``, which more often than not is not practical leading to issues like:

* ```ERROR: mlfinlab 0.10.0 has requirement numpy==1.17.3, but you'll have numpy 1.17.4 which is incompatible.```

I would suggest to switch to softer version requirements, e.g., `numpy>=1.17.3`. I think it's fairly safe to assume that numpy's (scipy's, matplotlib's, etc) changes/features addition won't break ``mlfinlab`` functionalities.

Thanks for this great package!

**Comment by aditya1702** [comment]
@mirca Thank you for opening the issue. We are aware of this issue and are working to fix it. Will hopefully have a fix soon 👍

**Comment by Jackal08** [comment]
Hi @mirca,

Thanks for this. I will fix it in the next version release.

**Comment by Jackal08** [comment]
I have added the soft dependencies in version 0.11.0.

Thanks for the great idea!
