### ISSUE TITLE
PSR ECs

### ISSUE THREAD

**Issue by rvvincelli** [hudson-and-thames/mlfinlab#324]
Hi team,

Thanks for this collection of tools, quite useful!

The so-called Probabilistic Sharpe Ratio by Prado et al. you implemented [here](https://github.com/hudson-and-thames/mlfinlab/blob/5c50c936ac039cbe27ff0203b9281ca0b7ef6ba7/mlfinlab/backtest_statistics/statistics.py#L259) lacks existence conditions. Those are not found in the original papers either, where the authors do provide a sound derivation, most probably neglecting pathological (yet not extreme) cases in the final result.

In particular, the function may return, `inf`, `nan` or a complex number, which of course do not make sense for the SR even if a CDF could formally be extended to the complex domain too.

Perhaps it is a known design choice, but users may like a diagnostic warning or even an error should any formula be undefined for a given input. This could be the case by other functions implemented in the library.

How to reproduce:
`probabilistic_sharpe_ratio(1.2, 1.0, 2, 2, 3)`

Thank you,

**Comment by Jackal08** [comment]
Hi @rvvincelli, 

Thanks for the issue. Tagging the author @PanPip.

**Comment by PanPip** [comment]
Due to a lack of existence conditions in the original works, checking if the input is valid might be tricky.

I'll add warnings to these functions informing the user when the output is inappropriate (`nan/inf/complex`) and what caused it.

**Comment by PanPip** [comment]
User warnings added to `probabilistic_sharpe_ratio` when the return is (`nan/inf/complex`) in PR #402.
