### ISSUE TITLE
Typo on documentation?

### ISSUE THREAD

**Issue by decastro-alex** [hudson-and-thames/mlfinlab#335]
I think the lines of code I quoted below are out of place. Base `price_events` is not used anywhere 

.. code-block::

    import pandas as pd
    from sklearn.ensemble import RandomForestClassifier
    from mlfinlab.ensemble import SequentiallyBootstrappedBaggingClassifier

    X = pd.read_csv('X_FILE_PATH', index_col=0, parse_dates = [0])
    y = pd.read_csv('y_FILE_PATH', index_col=0, parse_dates = [0])
    triple_barrier_events = pd.read_csv('BARRIER_FILE_PATH', index_col=0, parse_dates = [0, 2])
    price_bars = pd.read_csv('PRICE_BARS_FILE_PATH', index_col=0, parse_dates = [0, 2])

    triple_barrier_events = triple_barrier_events.loc[X.index, :] # take only train part

>     price_events = price_events[(price_events.index >= X.index.min()) &
>                                 (price_events.index <= X.index.max())]

    base_est = RandomForestClassifier(n_estimators=1, criterion='entropy', bootstrap=False,
                                   class_weight='balanced_subsample')
    clf = SequentiallyBootstrappedBaggingClassifier(base_estimator=base_est,
                                                    samples_info_sets=triple_barrier_events.t1,
                                                    price_bars=price_bars, oob_score=True)
    clf.fit(X, y)

**Comment by Jackal08** [comment]
Hi @PanPip, 

Can you please look into this for this weekends version bump?

**Comment by PanPip** [comment]
@Jackal08 Fixed this issue in #383. 

Also fixed other minor inconsistencies in the Feature Importance code examples.
