### ISSUE TITLE
CUSUM.py get_chu_stinchcombe_white_statistics multiprocessing issue

### ISSUE THREAD

**Issue by jasonharris438** [hudson-and-thames/mlfinlab#348]
This is the first time I've raised an issue, so if I have left out any detail please shoot me a msg and I'll add.
I have attached my environment specs in environment.txt:
[environment.txt](https://github.com/hudson-and-thames/mlfinlab/files/4707037/environment.txt)

See detail -

Description -
get_chu_stinchcombe_white_statistics() has an excessive running time, have stopped it after >1hr due to it not completing (I used a simulated dataset of 1000 observations, with a two_sided test). I left the default argument of num_threads=8 as is.

I suspect this is due to an issue with the multiprocessing library. I have stepped through the function call, and once execution enters the threading.py file (...\Anaconda\envs\env_mlfinlab\Lib\threading.py), creation of the Thread class is where execution becomes slow.

To check my logic, I then removed mp_pandas_obj() call from the cusum.py file and ran _get_s_n_for_t() directly, execution time was ~90ms. Based on this the issue is in the multiprocessing component.

To Reproduce -
1. from mlfinlab.structural_breaks.cusum import get_chu_stinchcombe_white_statistics
2. Prepare input data as per the required parameters.
3. get_chu_stinchcombe_white_statistics(series=input_series["log_price"], test_type="two_sided")

Expected behavior -
I expect the get_chu_stinchcombe_white_statistics() call to run forever with no end.

Desktop -

mlfinlab 0.10.0

compiler   :  MSC v.1915 64 bit (AMD64)
system     : Windows
version    : 1909 Build 18363.836
machine    : x64
processor  : Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, 3192 Mhz, 6 Core(s), 12 Logical Processor(s)

**Comment by PanPip** [comment]
@jasonharris438 thank you for reporting this issue.

Does the same issue occur with the new version of MlFinLab?

**Comment by jasonharris438** [comment]
Hi @PanPip, it seems to be fixed now, running time was 7.8 minutes for a simulated dataset of 10k points. I have another couple of things that I would like to raise about this function, should I raise a separate issue or pull request with changes?

**Comment by PanPip** [comment]
@jasonharris438 Great! Thanks for checking.

You can describe CUSUM enhancements in a separate Issue and then create a PR with these changes. I'll be happy to help with the PR once it's ready. 🙂

**Comment by jasonharris438** [comment]
Cool thanks @PanPip, my change solutions seem to work when I run in my local environment. I was wondering how do I run your unit tests? I'm new to this stuff and that's something I haven't done before.

**Comment by PanPip** [comment]
@jasonharris438 There are three things you should check:
1) Run a command `pylint new_file.py` for every file that you've changed to check if it fulfills the style requirements.
2) Go to `mlfinlab/tests` folder and run `python -m unittest test_new_file.py` for every test file that includes the functions that you've changed. Alternatively, you can do `python -m unittest discover` to run all tests.
3) Coverage is a tricky one to run locally, so after doing the first two tests you can make a commit and Travis CI will show the coverage.
