### ISSUE TITLE
Online Portfolio Selection

### ISSUE THREAD

**Issue by akwon31** [hudson-and-thames/mlfinlab#352]
Strategies to be implemented:

Momentum:
- Successive Constant Rebalanced Portfolio
- Online Newton Update
- Online Newton Step
- Online Gradient Update

Mean Reversion:
- Anti-Correlation
- Combination Forecasting Reversion Strategy

Pattern Matching:
- RACORN/RACORN-K
- Log-optimal Histogram/Kernel/Nearest-Neighbor
- Semi log-optimal Kernel
- Markowitz type Kernel
- GV type Kernel

Universal Portfolio:
- Aggregating Algorithm
- Switching Portfolio
- Follow the Leading History

Others:
- Risk-Adjusted Portfolio
- Combined Risk-Adjusted Portfolio

Features:
- Transaction Costs
- Short Selling

**Comment by akwon31** [comment]
@cschiri I think it will be a while until I start on the transaction costs. I'd assume that I'll calculate it by tracking the change in the number of assets and using bps to adjust the portfolio returns.

**Comment by cschiri** [comment]
Hi @akwon31 

Is this approach in harmony with the direction you envisage to follow:

```
# Estimate Transaction Costs

def estimate_transaction_cost(asset_prices, weights, transaction_cost=0.005):
    
    indexed_prices = asset_prices.divide(asset_prices.iloc[0])
    daily_transaction_count = ((weights != weights.shift(axis=0)).cumsum(axis=0)).diff()
    daily_transaction_count = daily_transaction_count.fillna(value=1)
    daily_costs = ((daily_transaction_count.mul(weights)).mul(indexed_prices)).mul(transaction_cost)
    daily_costs['total_transaction_costs'] = daily_costs.sum(axis=1)
    transaction_costs = daily_costs[['total_transaction_costs']] 
    
    return transaction_costs
```

The function takes three inputs:

1. The asset price frame which is fed into the online module.
2. The weights that are produced using the "strategy_name.all_weights" function.
3. A rough estimate of the transaction cost in percentage terms.

Best
-C

**Comment by cschiri** [comment]
Hi @akwon31 

On Estimating Transaction Costs for Online Strategies

I came up with a simple and crude Pandas-based methodology for computing online strategy transaction costs.

It uses three inputs:
1) Transaction Costs.
2) Weights of Portfolio Elements.
3) Cumulative Returns of the Portfolio.

And, it re-balances the portfolio at every bar.

See below:

```
# Get Weights and Returns from All Tickers

weights = strategy.all_weights
returns = strategy.portfolio_return
returns.columns = ["cummulative_strategy_returns"]


# Helper Function for Estimating Transaction Costs from Rebalancing Portfolio

def compute_net_cummulative_returns(returns, weights, transaction_costs=0.005):
    
    print("Total Weighting Changes Per Ticker:")
    print("")
    print((weights != weights.shift(axis=0)).sum(axis=0))

    gross_allocation = weights.mul(returns['cummulative_strategy_returns'], axis=0)
    net_allocation_absolute = np.abs(gross_allocation.diff())
    transaction_costs_per_share = net_allocation_absolute.mul(transaction_costs)
    transactions_costs_aggregate = pd.DataFrame(transaction_costs_per_share.sum(axis=1), columns=["aggregrate_costs"])
    profitability_elements = pd.concat([returns, transactions_costs_aggregate], axis=1)
    net_cummulative_returns = pd.DataFrame((profitability_elements["cummulative_strategy_returns"] - \
                                            profitability_elements["aggregrate_costs"]), 
                                            columns=["net_cummulative_returns"])

    return net_cummulative_returns


net_cummulative_returns = compute_net_cummulative_returns(returns, weights, transaction_costs=0.005)
net_cummulative_returns
```

Is the method in harmony with the other computations that are made by the sub-module? I just want to be sure that it is a
logically and mathematically sound approach.

Best
-C.

**Comment by akwon31** [comment]
@cschiri , Looks about right.

**Comment by aditya1702** [comment]
@Jackal08 any reasons for keeping this one open?

**Comment by Jackal08** [comment]
Hi @aditya1702, this is a list of algorithms that we can still implement in the OLPS module. So a type of ice bucket ticket.

**Comment by GXY2017** [comment]
About Short Selling
I dont think its very necessary to add short selling as part of the package. If I need to short sell, just put asset A (which is long ) and (-1)*A (which is short ) together, and then calculate the net weight of asset A in the portfolio.  Since it nets off some weight in asset A, it will leave some cash on hand, the sum of weight of each asset is not 100%.

**Comment by GXY2017** [comment]
Suggest PPN model in [Cost-Sensitive Portfolio Selection via Deep Reinforcement Learning](https://arxiv.org/pdf/2003.03051)

**Comment by Dhavin** [comment]
hi, @aditya1702 @Jackal08 I would like to contribute to the list of algorithms that we can implement in the OLPS module in this project. Can I?

**Comment by Jackal08** [comment]
Closing this ticket. OLPS is aslo part of PortfolioLab.
