### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by akwon31** [hudson-and-thames/mlfinlab#353]
**Describe the bug**
The directory structure for the package might be confusing for new users.

I was looking for the detoning and denoising matrix for a while until Jacques pointed it out that it was under Risk Estimators.

Could there be a way to improve visibility for these methods? It would be terrible for someone to unable to find what they need when it is actually in MlFinLab.

**Comment by PanPip** [comment]
Thanks for the proposition. I'll think of how it can be imporved.

Do you have some propositions about the new structure? 🙂

**Comment by akwon31** [comment]
What do you think about putting the correlation related ones in a different directory? The Risk Estimators and TIC can be used not only in portfolio optimization but also in other fields as well.

**Comment by PanPip** [comment]
I have created a separate toctree for Codependence measures in [PR#337](https://github.com/hudson-and-thames/mlfinlab/pull/337). I'll ask @aditya1702 on his thoughts regardiong this.

**Comment by Jackal08** [comment]
I am closing this issue. 

@PanPip is working on the TreeMap in his upcoming sprint.
