### ISSUE TITLE
documentation typing error

### ISSUE THREAD

**Issue by mohammadalimehdizadeh** [hudson-and-thames/mlfinlab#355]
In documentation, part 8.8.3 Examples :
from mlfinlab.codependece import distance_correlation, get_mutual_info, variation_of_information_score
is wrong typed!
correct one is:
from mlfinlab.codependence import distance_correlation, get_mutual_info, variation_of_information_score

**Comment by Jackal08** [comment]
Hi @mohammadalimehdizadeh,

Thanks for your feedback. Maybe I am missing it but did you maybe copy paste the same code? They look exactly the same to me. Where is the subtle difference?

**Comment by Jackal08** [comment]
Ah spelling typo on codependence

**Comment by PanPip** [comment]
Fixed in PR #337
