### ISSUE TITLE
setup.py causes problems with pandas version

### ISSUE THREAD

**Issue by gioxc88** [hudson-and-thames/mlfinlab#358]
the way you guys are generating the setup.py makes a requirement for pandas version==0.25.3.
This way any pipenv will fail to lock because many packages are incompatible with this requirement.

Can you change it to >=0.25.3?

Thank you

**Comment by Jackal08** [comment]
Hi @gioxc88,

We certainly need to migrate but right now pandas still has many breaking changes that both us and other packages need to resolve before we can upgrade.

Will be done in about the next 2 month.

**Comment by Jackal08** [comment]
You can run the unit tests locally to see all the places but for sure anything that includes the multiprocessing engine.

**Comment by Jackal08** [comment]
Hi @gioxc88, 

We are doing a version release this weekend to bump our dependencies to all the latest versions. Including the latest pandas. 

Best regards
Jacques
