### ISSUE TITLE
Synthetic Raw Data Generator

### ISSUE THREAD

**Issue by boyboi86** [hudson-and-thames/mlfinlab#360]
Hi mlfinlab team

With respect to chapter 2 (Data structure).

From my understanding I believe there might be some legal issues, if mlfinlab team were to share the actual raw data.

In that case, would the team be keen on using synthetic raw data. To demonstrate how dollar bars were formed? As well as ETF tricks?

I wrote a short code snippet for myself but I think it would be useful to new quants when it comes to learning the logic of how the data is being structured.

Here is the link to my gist: [synthetic data generator](https://gist.github.com/boyboi86/5e00faf48f60abfdbe838fbdee269471)

**Comment by Jackal08** [comment]
Hi @boyboi86, 

Thanks for sharing this idea. We need a couple of days to start going through all the Git issues. Will take some time, but you certainly have my attention. 

Best regards
Jacques

**Comment by Jackal08** [comment]
@dmunozc you are busing working on this specialisation, what do you think? Can ping me on slack.

**Comment by boyboi86** [comment]
Let me know if you guys require further assistance.

**Comment by PanPip** [comment]
@boyboi86 Thanks for sharing this! 🙂 

We're working on methods for generating synthetic codependence matrices for now. After this, we will move into generating synthetic time series.

As I understood from the code you've provided it generates a dataset based on normal dist of returns. We'd like to add a bit more advanced methods that would show more properties of the real data, as well as being more adjustable. It would be more interesting to run algorithms in the MlFinLab package on synthetic datasets like that.

**Comment by Jackal08** [comment]
That's an important point. That the synthetic data should share many of the properties of real data.

**Comment by Jackal08** [comment]
Closing: We have completed a synthetic data gen module.
