### ISSUE TITLE
unclear how to go from raw tick data to tick, volume and dollar bars

### ISSUE THREAD

**Issue by tingli81** [hudson-and-thames/mlfinlab#37]
Hi, 

I was looking at the file data_structures.py to see how you go from raw tick data to the desired outputs.  However, it's not clear to me since it says "The csv file must have only 3 columns: date_time, price, & volume".  However, in the sample E Mini file downloaded from TickData I was given two files.  ES_Quotes.csv and ES_Trades.csv.   Which file are you using?  Do you have to make some adjustments to these files?

Best,

Ting

**Comment by Jackal08** [comment]
Hi @tingli81,

So the master and dev branch right now as you have it is a bit outdated. At the end of our sprint this week we are going to merge in a number of changes, including: Standard, Imbalance, and Run bars. The ETF trick and code from ch3 regarding labeling and filters. 

The data you are refering to is the raw data provided by TickData LLC. If you purchase their software then you will be able to make use of TickWrite7 to improve the saved csv files. 

At the moment we require users to create a new csv file based on thier data that has only 3 columns, date_time, price, and volume. The reason for this is to minimise the size of the csv file. We have some files over 21 gigs. 

At a later stage we will let the user define which columns to use in the dataframe but it will mean that it takes longer to run. 

Let me know if you have any further questions. 

Best regards
Jacques Joubert

**Comment by tingli81** [comment]
Hi Jaqcues,

Apologies, this is due to the fact that I’m not a professional programmer.  However, I’ve been going through your latest push on Github.

Is there a way to provide some more explicit directions on how to transform the data into the required formats.  I see the files in data_structures but I don’t see any directions and raw file where I can see what the input and output are.

Best,

Ting

**Comment by Jackal08** [comment]
Hi Ting. 

I am busy preparing a couple of tutorial notebooks for a meet up we are hosting in London. I will be sure to publish those around the 23 of May 2019. They will provide a full explanation and analysis of the various functions.

**Comment by Jackal08** [comment]
Hi @tingli81,

I have added a notebook to provide an end to end walkthrough of creating the data structures. 

https://github.com/hudson-and-thames/research/blob/master/Chapter2/Getting%20Started.ipynb
