### ISSUE TITLE
Create a tree of MLFinLab features

### ISSUE THREAD

**Issue by PanPip** [hudson-and-thames/mlfinlab#376]
Create a tree structure/list description of features currently available in the package to avoid confusion and present packages to new users. Will also solve the problem of not knowing what each module contains, as in [Issue#353](https://github.com/hudson-and-thames/mlfinlab/issues/353)

**Comment by aditya1702** [comment]
This is a great idea! Lets finish this quickly!

**Comment by PanPip** [comment]
PS. This idea resulted in creating the index of research notebooks: https://mlfinlab.readthedocs.io/en/latest/getting_started/research_notebooks.html
