### ISSUE TITLE
Online Strategies: Optuna Hyper Parameter Optimization Raw Scripts

### ISSUE THREAD

**Issue by cschiri** [hudson-and-thames/mlfinlab#392]
Regards @akwon31 

Is it possible for you to upload the raw scripts that were used to discover the optimum hyper-parameter settings for the online strategies? 

In the research section, there are scripts that summarize the results of Optuna parameter optimization exercises.

I am more interested in understanding how you structured the parameter search problem, using Mlfinlab and Optuna (in general).

**Comment by akwon31** [comment]
@cschiri 

I included two scripts that you can use as a reference.

https://github.com/hudson-and-thames/research/tree/master/Online%20Portfolio%20Selection

The first script creates the Optuna study and then has a list of all the objective functions for each strategy.
The second script has an example of actually running it.

**Comment by cschiri** [comment]
Thank you Alex
