### ISSUE TITLE
Fix tail set labeling to allow for user input quantile

### ISSUE THREAD

**Issue by ruifanp** [hudson-and-thames/mlfinlab#404]
The docstring in the tail set labeling method states: "A tail set is defined to be a group of stocks whose volatility-adjusted price change is in the highest or lowest quantile, for example the highest or lowest 5%." However, currently the only tail sets found are the top and bottom decile. Will fix to allow user input for quantile.

**Comment by PanPip** [comment]
This feature was added in PR #406.
