### ISSUE TITLE
there is a typo

### ISSUE THREAD

**Issue by zhangyw49** [hudson-and-thames/mlfinlab#427]
https://github.com/hudson-and-thames/mlfinlab/blob/8202463b669cbd6b20a6a75a649bdc5e9c8cb5b3/mlfinlab/portfolio_optimization/mean_variance.py#L178

**Comment by zhangyw49** [comment]
line 185  print("Portfolio Sharpe Ratio = %s" % self.portfolio_risk)

**Comment by aditya1702** [comment]
@zhangyw49 Thank you for spotting this. Pushing a fix asap.

**Comment by PanPip** [comment]
@zhangyw49 Thank you for reporting this issue! 🙂 

It is now fixed in PR #426. Soon it will be pushed to the `master` branch.
