### ISSUE TITLE
Is this an error in the computing weights in HERC

### ISSUE THREAD

**Issue by zhangyw49** [hudson-and-thames/mlfinlab#428]
In the Step3:
$$\alpha_1 = \frac{RC_1} {RC_1 + RC2}$$

the correct form may be:
$$\alpha_1 = 1 - \frac{RC_1} {RC_1 + RC2}$$

**Comment by zhangyw49** [comment]
Ok, the code is correct:

  line 296              alloc_factor = 1 - left_cluster_contribution / (left_cluster_contribution + right_cluster_contribution)

**Comment by Jackal08** [comment]
Hi @zhangyw49,

Has this ticket been resolved?

**Comment by PanPip** [comment]
@Jackal08 I'll add a fix to this bug (change description as described in the first comment) in PR #422

**Comment by zhangyw49** [comment]
In the [documents](https://mlfinlab.readthedocs.io/en/latest/portfolio_optimisation/hierarchical_equal_risk_contribution.html)
"At each level of the tree, an Equal Risk Contribution allocation is used i.e. the weights are:"
$$\alpha_1 = \frac{RC_1} {RC_1 + RC2}$$
and so it is in orginal peper

but i think the correct form might be:
$$\alpha_1 = 1 - \frac{RC_1} {RC_1 + RC2}$$

I want to know which is the correct answer?

**Comment by PanPip** [comment]
@zhangyw49 You're right, the second form is correct.

**Comment by PanPip** [comment]
@zhangyw49 Done 🙂

It is now fixed in PR #422. Soon it will be pushed to the `master` branch.
