### ISSUE TITLE
trend_scanning_labels.t_value is negative and huge for sample weights

### ISSUE THREAD

**Issue by segatrade** [hudson-and-thames/mlfinlab#433]
**Describe the bug**
"The t-values can be used as sample weights in classification problems."
trend_scanning_labels.t_value is negative and huge for sample weights:

t_value
mean        2.120635   
std      1823.624485     
min   -277552.971526    
25%        -5.119581    
50%        -1.234035     
75%         5.196217   
max    153424.198288   

**To Reproduce**
1. trend_scanning_labels(dataset['close'], t_events, look_forward_window=20,  min_sample_length=5)

**Expected behavior**
trend_scanning_labels.t_value is positive and smaller for sample weights.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by MislavSag** [comment]
I have just checked min and max values for t1 trend scanning variable. Max value is 235 and min value -208.

Without data it's hard to identify the problem.

**Comment by segatrade** [comment]
input: [2020_07_27-dataset_close.pkl.compress.zip](https://github.com/hudson-and-thames/mlfinlab/files/4982895/2020_07_27-dataset_close.pkl.compress.zip)

output: [goal-trend_scanning-2020-07-27.pkl.compress.zip](https://github.com/hudson-and-thames/mlfinlab/files/4982843/goal-trend_scanning-2020-07-27.pkl.compress.zip) - takes approx 9 minutes on my machine. sample_weight=t_value , long=(bin==1)

import joblib

dataset=joblib.load('your_path/2020_07_27-dataset_close.pkl.compress')

import numpy as np
import pandas as pd

from mlfinlab.labeling import trend_scanning_labels
t_events= dataset.index
tr_scan_labels = trend_scanning_labels(dataset['close'],t_events, 
                                       look_forward_window=20, 
                                       min_sample_length=5)

**Comment by PanPip** [comment]
@segatrade Thank you for reporting this issue!

I've looked into the code and it's written as intended in the **Advances in Financial Machine Learning** by _Lopez de Prado_ (page 258).

The issue here is that for some regressions the variations of betas were too small resulting in high SADF estimates. 
![sadf](https://user-images.githubusercontent.com/16906989/88802245-16c76300-d1ab-11ea-9bbd-73d684834f59.png)
[Reference](https://mlfinlab.readthedocs.io/en/latest/implementations/structural_breaks.html#supremum-augmented-dickey-fuller)

A solution to this can be increasing the minimum sample length (setting it to 6 already removes the high negative SADF value at 2019-12-18 19:03 observation).

**Comment by rspadim** [comment]
maybe penalize by n sqrt(sigma) ?

**Comment by PanPip** [comment]
In this case, I'd say that penalizing would need to be adjusted for this specific problem, as the anomaly numbers are pretty high in relation to the standard ones. Different datasets and input variables would require different penalization adjustments, so I don't think it's a good option to add one general penalization method here.

An option would be to install mlfinlab package locally using `pip install -e mlfinlab` and adjust `get_betas` function in `mlfinlab/structural_breaks/sadf.py`

Let me know if you'll be playing around with it and will come to a general solution 🙂

**Comment by rspadim** [comment]
you told about sadf, but the problem is t-value of linreg (labelling function)

**Comment by PanPip** [comment]
@rspadim But the t-value is calculated from the mean and std from `get_betas` function of the `sadf.py`

https://github.com/hudson-and-thames/mlfinlab/blob/1d26d6d436d9ee5122d34ea471e09fd927bb94ac/mlfinlab/labeling/trend_scanning.py#L62-L69

**Comment by rspadim** [comment]
https://github.com/hudson-and-thames/mlfinlab/blob/1d26d6d436d9ee5122d34ea471e09fd927bb94ac/mlfinlab/labeling/trend_scanning.py#L65

A non penalized metric

**Comment by PanPip** [comment]
In this case `n sqrt(sigma)` wouldn't fix such big anomalies as -107375. I mean, which general penalization method do you think would fit here?

**Comment by rspadim** [comment]
sorry now i checked https://github.com/hudson-and-thames/mlfinlab/blob/master/mlfinlab/structural_breaks/sadf.py#L152
it's already the standard error (shape adjusted)

**Comment by rspadim** [comment]
the best penalization is the window size, no solution here

other option is use of inverse entropy or entropy of t-values instead directly t-values

**Comment by rspadim** [comment]
others possibilities are, filter the t-value series (kalman maybe) or moving average, but the effect is near to change window sizes

**Comment by PanPip** [comment]
Thanks @rspadim 🙂 

I guess this issue is solved now.
