### ISSUE TITLE
Windows install problems

### ISSUE THREAD

**Issue by Jackal08** [hudson-and-thames/mlfinlab#437]
Hi @PanPip, 

When we get some time, can we please add these install instructions for windows users to Readme and Sphinx.

https://medium.com/@kegui/how-to-install-mlfinlab-without-error-messages-896e2fb43c2f

Thanks!

**Comment by PanPip** [comment]
@Jackal08 Okay, I will work on that 🙂

**Comment by PanPip** [comment]
This issue will be fixed in PR #449.
