### ISSUE TITLE
How to use GPU for pattern matching?

### ISSUE THREAD

**Issue by sword134** [hudson-and-thames/mlfinlab#438]
How does one enable GPU for calculating pattern matching? The pattern matching can take quite a long time running on the CPU so how do I run it on GPU instead?

**Comment by Jackal08** [comment]
I'm pretty sure that you cant use the GPU for these operations.

Is there a source in the documentation that says you can?

**Comment by sword134** [comment]
@Jackal08 no there isnt a source in the documentation, that's why I came here to ask whether or not it would be possible.

**Comment by Jackal08** [comment]
Ah ok, no - it's not possible :)
