### ISSUE TITLE
What happened to the code?

### ISSUE THREAD

**Issue by FrithiofJensen** [hudson-and-thames/mlfinlab#443]
Hi! 

I am pretty sure that just a week ago, there was actual code in at least some of the functions (trend scanning, for example). Suddenly, every function implementation seems to be "pass" which is indeed valid code but not, perhaps, what one expects to install -> This update will break a lot of containers!

I would like to see this straight away on the landing page so I know immediately not to bother anyone further with that project (or buy the damn book and type it in myself).  

Best regards!

**Comment by PanPip** [comment]
Hi @FrithiofJensen!

All the implementations are available for use if you install MlFinLab from PyPi.

**Comment by Jackal08** [comment]
Hi @FrithiofJensen,

We are in the process of moving towards an open-core model. All the code is currently all free to use via the pypi pip install mlfinlab. 

We have moved the source code to a private repo and are busy making all the changes to docs, the public repo, and so on. 

The good news is that all the value add ons can be purchased via our [Patroen](https://www.patreon.com/HudsonThames) page.

Do let us know if you have any questions and we invite you to join us on Slack.

Best regards
Jacques

**Comment by samatix** [comment]
Hi @Jackal08 

I fully recognize that you and all of the other contributors have done a lot of effort to read the research articles and implement them.

However, it is not cool to move all of the code that already has a very restrictive license, to a premium repo accessible for an expensive monthly subscription fee. 

Thanks,
Ayoub

**Comment by Jackal08** [comment]
Hi @samatix,

All the code is still available for use via a `pip install mlfinlab`. The only thing you qould really need to maximise use is the 50

**Comment by PoCk3T** [comment]
https://github.com/FriendlyUser/mlfinlab
