### ISSUE TITLE
T-statistics test in onc.py

### ISSUE THREAD

**Issue by emoen** [hudson-and-thames/mlfinlab#445]
**Describe the bug**
Should if new_tstat_mean > mean_redo_tstat:
be: if new_tstat_mean <= mean_redo_tstat: ? This is how its written in the ML for asset managers -book.

since you stop calculating the clusters when the t-statistics is less than the expected redo_t-statistics?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]

**Comment by PanPip** [comment]
Thanks for noticing, @emoen! This issue will soon be fixed.

**Comment by Jackal08** [comment]
Hmm be careful when making changes. I seem to remember that we did this deliberately.

**Comment by PanPip** [comment]
@emoen This issue was fixed in the current release of MlFinLab version 0.13.0.
