### ISSUE TITLE
Importing get_weights_by_return() throws numba-related error

### ISSUE THREAD

**Issue by pmgh2345** [hudson-and-thames/mlfinlab#448]
**Describe the bug**
After much trouble installing mlfinlab (first Visual C++ version, then an issue whereby pip couldn't uninstall llvmlite as part of the mlfinlab install, preventing installation), I was finally able to do so with ` pip install mlfinlab --ignore-installed llvmlite`

Then, returning to a script I have that makes use of get_weights_by_return(), simply importing that function threw me the following error:

> ~\Desktop\Python\Project\prepare_modeling_data.py in <module>
      4 
      5 import pandas as pd, numpy as np
----> 6 from mlfinlab.sample_weights.attribution import get_weights_by_return
      7 from sklearn.model_selection import train_test_split
      8 

~\Anaconda3\envs\x2\lib\site-packages\mlfinlab\__init__.py in <module>
      7 
      8 import mlfinlab.cross_validation as cross_validation
----> 9 import mlfinlab.data_structures as data_structures
     10 import mlfinlab.datasets as datasets
     11 import mlfinlab.multi_product as multi_product

~\Anaconda3\envs\x2\lib\site-packages\mlfinlab\data_structures\__init__.py in <module>
     14 """
     15 
---> 16 from mlfinlab.data_structures.imbalance_data_structures import get_ema_dollar_imbalance_bars, \
     17     get_ema_volume_imbalance_bars, \
     18     get_ema_tick_imbalance_bars, get_const_dollar_imbalance_bars, get_const_volume_imbalance_bars, \

~\Anaconda3\envs\x2\lib\site-packages\mlfinlab\data_structures\imbalance_data_structures.py in <module>
     27 import pandas as pd
     28 
---> 29 from mlfinlab.data_structures.base_bars import BaseImbalanceBars
     30 from mlfinlab.util.fast_ewma import ewma
     31 

~\Anaconda3\envs\x2\lib\site-packages\mlfinlab\data_structures\base_bars.py in <module>
     10 import pandas as pd
     11 
---> 12 from mlfinlab.util.fast_ewma import ewma
     13 
     14 

~\Anaconda3\envs\x2\lib\site-packages\mlfinlab\util\__init__.py in <module>
      3 """
      4 
----> 5 from mlfinlab.util.fast_ewma import ewma
      6 from mlfinlab.util.multiprocess import expand_call, lin_parts, mp_pandas_obj, nested_parts, process_jobs, process_jobs_, \
      7     report_progress

~\Anaconda3\envs\x2\lib\site-packages\mlfinlab\util\fast_ewma.py in <module>
      7 # Imports
      8 import numpy as np
----> 9 from numba import jit
     10 from numba import float64
     11 from numba import int64

~\Anaconda3\envs\x2\lib\site-packages\numba\__init__.py in <module>
    296 
    297 # Initialize typed containers
--> 298 import numba.typed

~\Anaconda3\envs\x2\lib\site-packages\numba\typed\__init__.py in <module>
----> 1 from .typeddict import Dict
      2 from .typedlist import List

~\Anaconda3\envs\x2\lib\site-packages\numba\typed\typeddict.py in <module>
     20 
     21 
---> 22 @njit
     23 def _make_dict(keyty, valty):
     24     return dictobject._as_meminfo(dictobject.new_dict(keyty, valty))

~\Anaconda3\envs\x2\lib\site-packages\numba\core\decorators.py in njit(*args, **kws)
    234         warnings.warn('forceobj is set for njit and is ignored', RuntimeWarning)
    235     kws.update({'nopython': True})
--> 236     return jit(*args, **kws)
    237 
    238 

~\Anaconda3\envs\x2\lib\site-packages\numba\core\decorators.py in jit(signature_or_function, locals, target, cache, pipeline_class, boundscheck, **options)
    171                    targetoptions=options, **dispatcher_args)
    172     if pyfunc is not None:
--> 173         return wrapper(pyfunc)
    174     else:
    175         return wrapper

~\Anaconda3\envs\x2\lib\site-packages\numba\core\decorators.py in wrapper(func)
    187         disp = dispatcher(py_func=func, locals=locals,
    188                           targetoptions=targetoptions,
--> 189                           **dispatcher_args)
    190         if cache:
    191             disp.enable_caching()

~\Anaconda3\envs\x2\lib\site-packages\numba\core\dispatcher.py in __init__(self, py_func, locals, targetoptions, impl_kind, pipeline_class)
    668         """
    669         self.typingctx = self.targetdescr.typing_context
--> 670         self.targetctx = self.targetdescr.target_context
    671 
    672         pysig = utils.pysignature(py_func)

~\Anaconda3\envs\x2\lib\site-packages\numba\core\registry.py in target_context(self)
     45             return nested
     46         else:
---> 47             return self._toplevel_target_context
     48 
     49     @property

~\Anaconda3\envs\x2\lib\site-packages\numba\core\utils.py in __get__(self, instance, type)
    330         if instance is None:
    331             return self
--> 332         res = instance.__dict__[self.name] = self.func(instance)
    333         return res
    334 

~\Anaconda3\envs\x2\lib\site-packages\numba\core\registry.py in _toplevel_target_context(self)
     29     def _toplevel_target_context(self):
     30         # Lazily-initialized top-level target context, for all threads
---> 31         return cpu.CPUContext(self.typing_context)
     32 
     33     @utils.cached_property

~\Anaconda3\envs\x2\lib\site-packages\numba\core\base.py in __init__(self, typing_context)
    257 
    258         # Initialize
--> 259         self.init()
    260 
    261     def init(self):

~\Anaconda3\envs\x2\lib\site-packages\numba\core\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~\Anaconda3\envs\x2\lib\site-packages\numba\core\cpu.py in init(self)
     45     def init(self):
     46         self.is32bit = (utils.MACHINE_BITS == 32)
---> 47         self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
     48 
     49         # Add ARM ABI functions from libgcc_s

~\Anaconda3\envs\x2\lib\site-packages\numba\core\codegen.py in __init__(self, module_name)
    643         self._llvm_module.name = "global_codegen_module"
    644         self._rtlinker = RuntimeLinker()
--> 645         self._init(self._llvm_module)
    646 
    647     def _init(self, llvm_module):

~\Anaconda3\envs\x2\lib\site-packages\numba\core\codegen.py in _init(self, llvm_module)
    652         self._tm_features = self._customize_tm_features()
    653         self._customize_tm_options(tm_options)
--> 654         tm = target.create_target_machine(**tm_options)
    655         engine = ll.create_mcjit_compiler(llvm_module, tm)
    656 

TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'

**To Reproduce**
`from mlfinlab.sample_weights.attribution import get_weights_by_return`

**Expected behavior**
I have had no problem running this before my last conda environment crashed.  Nevertheless, I have checked my package versions vs. mlfinlab's dependencies and everything is up to date- numba 0.49.1 and llvmlite 0.33.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jackal08** [comment]
Hi @pmgh2345,

Dont just ignore llvmlight, you need to manualyy delete it from your environment by using explorer. This error relates to Numba and llvmlight, and I think yours is broken. Best to remove and reinstall llvmlight and numba. 

I had this problem last night as well.

**Comment by PanPip** [comment]
I think we can do a FAQ with links to issues like this so users will know where to find solutions. What are your thoughts on this @Jackal08?

**Comment by pmgh2345** [comment]
Hey guys, I was able to resolve by rebuilding the environment with python 3.6, removing llvmlite in conda, then manually removing the folder per @Jackal08 's suggestion. At that point, however, I was unable to remove numba in the same way- I believe it must've been uninstalled when I got rid of llvmlite. I then installed mlfinlab straght from there, at which point pip presumably took care of reinstalling llvmlite and numba. At that point, my script that was giving me the problem earlier performed just fine 👍 
Thanks fellas!

**Comment by aspirina765** [comment]
I really would like to be a sponsor (a lot of work would be saved), but I could not even install the package.

**Comment by Jackal08** [comment]
Hi @aspirina765, 

Thanks for reaching out. Sorry to hear that you are having problems with the install. Maybe we can help. Please can you share the error message. 

I assure you that we have extensive tests for the package so it's either that you are using an old version of python < 3.6 or you don't have the correct dependencies. 

Best regards
Jacques Joubert

**Comment by aspirina765** [comment]
Hi @Jackal08 , I was able to install the package. 

I am grateful for your attention by sending me an email offering to help me. Much work will be saved.

Thanks again.
