### ISSUE TITLE
Where Can I get the docs that you changed before?

### ISSUE THREAD

**Issue by rwayan** [hudson-and-thames/mlfinlab#450]
a lots of docs have a lock there? 
where is the version of docs before you added a lock i can access?

**Comment by Jackal08** [comment]
Hi @rwayan,

All of our products are available via our [Patreon page](patreon.com/HudsonThames). If you are already a member, all the details will be in your inbox.

Please so let us know if you have any questions.

**Comment by rwayan** [comment]
but the docs are open source document now you closed source now ? 
may i access the archive of the old one?

**Comment by Jackal08** [comment]
Hi @rwayan,

The only way to get access to the docs is to pay for them.

**Comment by timkpaine** [comment]
@rwayan you can grab a [fork](https://github.com/hudson-and-thames/mlfinlab/network/members) and regenerate the html docs yourself
