### ISSUE TITLE
Allow Non-daily Dataframe in OLPS Models

### ISSUE THREAD

**Issue by GXY2017** [hudson-and-thames/mlfinlab#452]
**Is your feature request related to a problem? Please describe.**
When I try to test hourly data using OLMAR model, it requires daily data and cannot go down to hourly, minutes data. 

**Describe the solution you'd like**
Allow data index in hours, minutes or just steps in integer numbers.

**Comment by Jackal08** [comment]
Hi @GXY2017, 

I really don't think these algorithms would realistically work on the hourly time frame. 

I am open-minded if you would like to make a strong argument in favour of this.

**Comment by GXY2017** [comment]
1.  These OLPS methods can be used to higher frequency when I use the datetime format correctly.  So this issue is closed. 
2.  As authors have mentioned in essays,  these OLPS can be used in high frequency trading. The math they use does not restrict on this. 
3.  I tested more products besides ETFs and benchmarks. To share some results,  1)  these OLPS methods may describe the price movement in certain time period of each product, but cannot fits for all time.  2) I would say one method may fit the price movement best for a time rather than which method is the best all the time.
