### ISSUE TITLE
NCO _cluster_kmeans_base algorithm iterates n_init-1 number of times

### ISSUE THREAD

**Issue by emoen** [hudson-and-thames/mlfinlab#455]
**Describe the bug**
The documentation of _cluster_kmeans_base in nco.py states:
"The algorithm iterates n_init number of times and initialises K-Means with different seeds"

but the loop iterates n_init-1 number of times with:
        # Iterating over the allowed iteration times for k-means
        for init in range(1, n_init):

**Expected behavior**
Should be:
        # Iterating over the allowed iteration times for k-means
        for init in range(0, n_init):

**Comment by PanPip** [comment]
Hi @emoen!

Using `init=0` in this case is not right, as the KMeans algorithm won't run and will result in a `ValueError: Invalid number of initializations. n_init=0 must be bigger than zero.`

**Comment by emoen** [comment]
@PanPip there are several solutions to that. Either use 
```
for init in range(1, n_init+1): 
``` 
or 
```
KMeans(n_clusters=num_clusters, n_init=init+1)
```
or update the documentation:
:param n_init: (float) Number of time -1 the k-means algorithm will run with different centroid seeds (default 9)

**Comment by PanPip** [comment]
To be more precise, we can add the first solution to the new package version.

**Comment by PanPip** [comment]
A fix to this Issue is added and will available in the new version of the MlFinLab package.
