### ISSUE TITLE
NCO _cluster_kmeans_base "round half to even" use floor/ceiling

### ISSUE THREAD

**Issue by emoen** [hudson-and-thames/mlfinlab#456]
**Describe the bug**
NCOpy in the _cluster_kmeans_base method
If max_num_clusters is None then
max_num_clusters = round(corr.shape[0] / 2)

but round() uses "round half to even" strategy. So round(2.5) = 2 and round (3.5)=4
So could a 5x5 correlation matrix have max 2 clusters and a 7x7 matrix have max 4 clusters?

Seems better to use ceil (or floor) function.

**Comment by PanPip** [comment]
Hi @emoen!

It's possible to use the `max_num_clusters` variable in the `allocate_nco()` to set the maximum number of clusters equal to the number of variables in the input matrix.

**Comment by emoen** [comment]
@PanPip - if the user dont provide the argument it is better to use a consistent rounding. E.g have a 7x7 it allows 4 cluster. So there may be a cluster of just one element. Reconsidering floor() is probably better than ceil().

**Comment by PanPip** [comment]
If the clustering where there is only one element in a cluster has a higher clustering quality, what's the problem?

**Comment by emoen** [comment]
A cluster is more than 1 elements.

**Comment by PanPip** [comment]
If we have a set of 4 elements, three of them have small distances between each-other, and the fourth one is a distant outlier. 

How should we cluster them?

**Comment by emoen** [comment]
Good point, the distant outlier should be in a separate cluster. It is the use of round() i think should be changed because round uses "round half to even" strategy.
Lets say the covariance matrix is 3x3 than round(3./2) = 2. So lets say there are 3 elements, 2 close to each other, and 1 outlier. So you get 2 clusters. Then you add 2 elements which are close to each other but not to any of the other 3 elements. Then round(5./2) = 2 (!). So you only have 2 clusters. First cluster with the 2 last elements and second cluster is going to contain the cluster from the 3x3 matrix.

In which of the 2 clusters does the outlier go?
