### ISSUE TITLE
Change install_requires to >=

### ISSUE THREAD

**Issue by bububut** [hudson-and-thames/mlfinlab#457]
Thank you for this great library!
I would like to use mlfinlab in my conda environment, but currently it requires very specific version of all the depended libs. So the pip will downgrade my current installation e.g. from my pandas version 1.1.0 to 1.0.4.
Is it possible to change install_requires from == to >= so that I can install it in my current environment without downgrade other libs?

**Comment by bububut** [comment]
thanks for your help! I'll try with --no-deps

**Comment by PanPip** [comment]
Don't forget to install other libs from the config file if using `--no-deps`

https://github.com/hudson-and-thames/mlfinlab/blob/master/setup.cfg#L47-L63
