### ISSUE TITLE
Enable handling detoned covariance matrix in portfolio optimization

### ISSUE THREAD

**Issue by mjvakili** [hudson-and-thames/mlfinlab#458]
**Handling detoned covariance matrix in portfolio optimization methods that rely on inverse covariance matrix**

The detoned covariance matrix is singular. This is not an issue for clustering purposes (kmeans or hierarchical). 
However, it is problematic in the allocation step in which we have to take the inverse of the covariance matrix to calculate the weights. 

I was wondering if you have any plan on adding this functionality.

**Comment by aditya1702** [comment]
@mjvakili Thank you for raising this issue. Yes, the singularity of covariance matrix seems to be having issues with portfolio optimisation. I think this an important issue which needs to be addressed. Will add a solution for this soon and hopefully by our next release.

Will update this issue whenever we add it to the library

**Comment by aditya1702** [comment]
@mjvakili One solution is to check if the matrix is singular or not and if it is, then we take a pseudo-inverse rather than the normal inverse. 

Btw in which portfolio algorithm were you encountering this issue?

**Comment by mjvakili** [comment]
@aditya1702 I think by construction, a detoned covariance matrix will be singular (since we drop the term(s) corresponding to the highest eigenvalue(s) in in the eigenvector decomposition). 

We encounter this issue in any portfolio algorithm that involves taking the inverse of the covariance matrix such as: minimum variance and Nested Cluster Optimization

**Comment by aditya1702** [comment]
@mjvakili Yes agreed. I think this is a good feature to add to the library. I am already working on adding it and will notify when it is finished and available for use

**Comment by PanPip** [comment]
@mjvakili Thank you again for raising this issue.

It is now fixed in MlFinLab v. 0.15.0. The NCO and the CLA portfolio optimization algorithms were adjusted to handle singular covariance matrices.

Thank you @aditya1702 for the changes.
