### ISSUE TITLE
bump pandas >= 1.10

### ISSUE THREAD

**Issue by bobcolner** [hudson-and-thames/mlfinlab#464]
Pandas 1.10 supports the arrow/feather version 2.0 format which simplifies sharing complex data-set across platforms and languages.

**Comment by timolson** [comment]
Can I request that you use >= for all your packages that don't need exact versions?  Pinned versions are _horrendous_ for compatibility when importing mlfinlab into an existing project.  I'm forced to downgrade many packages to use mlfinlab :((((

**Comment by Jackal08** [comment]
Hi @timolson, 

Unfortunately, there doesn't seem to be a good way to handle package versioning. The reason we peg to specific versions is to ensure that all the code is stable and tested on those versions. 

Often when a package like pandas updates, it has breaking changes and that causes a lot of problems for us. For this reason, we can't use your suggested `>=` solution.

At the moment we update all the dependencies once a year to the latest versions and then keep them constant. 

If you have a good way to manage package dependencies without requiring a lot of overhead for the development team. We are all ears. 

Best regards
Jacques
