### ISSUE TITLE
Where to find unit tests?

### ISSUE THREAD

**Issue by kenluck2001** [hudson-and-thames/mlfinlab#465]
This is currently a lack of unit testing on contributed modules to this library. This is problematic on multiple levels. 
- Regression is guaranteed to occur and then we depend on people with domain knowledge for triage.
- Optimizing code is more difficult as there is no benchmark.

**Comment by Jackal08** [comment]
Hi @kenluck2001,

I would argue that we have quite a lot of unit tests, in fact our code has 100% coverage. That being said, there are only 1 or 2 modules with light tests.

Why are you under the impression that we dont have tests?

**Comment by kenluck2001** [comment]
I was looking across the code base and did not see any folder with name test or documentation on how to run the test. Please add to the readme how to run test. It would help newcomers know where to add their test and run the test.

**Comment by Jackal08** [comment]
@kenluck2001 I am a little confused. Where are you referencing the source code from? The PyPi package or the client folder? There is a test file and running the tests are covered in the docs. What source are you referencing that doesn't have those files?

**Comment by kenluck2001** [comment]
Thanks so much for getting back to me. I just cloned the master repo using
git clone https://github.com/hudson-and-thames/mlfinlab.git

This is the version that I currently have as I am attempting to build from source. Please just write the link to the test folder as I can't find it.

**Comment by Jackal08** [comment]
Ah I see, that repo is just a shell for users to post issues and it compiles the public docs, there is no actual source code in it. 

The source code is only available to clients and members of the H&T team. (However the PyPi package is available to the public)

We do have an [apprenticeship program](https://hudsonthames.org/apprenticeship-program/) that may interest you. Its this program that leads to the development of new modules. Applications are open until the 23rd of October. 

Outside of the program, there isn't a way to contribute to the library.

**Comment by Jackal08** [comment]
Thank you, keep well.
