### ISSUE TITLE
Followed mlfinlab installation for mac, however ModuleNotFoundError stopping import

### ISSUE THREAD

**Issue by lachlanmichalski** [hudson-and-thames/mlfinlab#466]
**Describe the bug**
 Followed the installation for mac and it was succesful, however when trying to import any packages, I get the error:
ModuleNotFoundError: No module named 'mlfinlab'

![Screen Shot 2020-10-23 at 11 34 04 pm](https://user-images.githubusercontent.com/70327616/97059342-165f1e00-1588-11eb-8c5a-ede94d52ab11.png)

The virtual environment is running as indicated, any ideas why this is happening?

**Expected behavior**
For there to not be a ModuleNotFoundError

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10.15.6

**Comment by Jackal08** [comment]
I have checked the install and confirmed that its working on Mac.

Are you installing the library via the PyPi index? As in 'pip install mlfinlab'? 

If you type pip freeze, can you please confirm that mlfinlab is installed locally?

**Comment by lachlanmichalski** [comment]
![Screen Shot 2020-10-24 at 12 32 40 am](https://user-images.githubusercontent.com/70327616/97061841-3c88bc00-1590-11eb-84f5-6cebcf1799b8.png)

Can confirm it is installed locally

**Comment by Jackal08** [comment]
Hmm and you are using the same environment in your notebook?

**Comment by lachlanmichalski** [comment]
I have the environment running, would I check if anaconda is using the same environment?

**Comment by Jackal08** [comment]
Its a little hard to do desktop support in this way but I can confirm that the library is working as intended and it seems like your local env can't find your installation. The Slack channel is a good place to ask these questions. :)
