### ISSUE TITLE
Bad link in docs

### ISSUE THREAD

**Issue by gerardsimons** [hudson-and-thames/mlfinlab#472]
A very minor one: the link in the [docs](https://mlfinlab.readthedocs.io/en/latest/) where it says  join the Slack channel actually links to the Patreon page rather than the Slack channel

**Comment by Jackal08** [comment]
Hi @gerardsimons, 

Thank you, thats because the Slack channel is a paid-for service under the Newbie tier at $10 a month +VAT. If you're looking to get fast feedback on questions and join a community of like-minded peers, we highly recommend it.

**Comment by gerardsimons** [comment]
Ah, my bad! Still, it might not be clear that that is the case from just the link.

**Comment by gerardsimons** [comment]
Is it the same for this link by the way? https://github.com/Hudson-and-Thames-Clients/research/tree/master/Sample-Data found here : https://mlfinlab.readthedocs.io/en/latest/getting_started/barriers_to_entry.html
