### ISSUE TITLE
Functions return NoneType

### ISSUE THREAD

**Issue by tobemo** [hudson-and-thames/mlfinlab#476]
**Describe the bug**
Calling a function returns a NoneType.
I first noticed it with `ml.labeling.get_events()` but it also occurs with `ml.util.get_daily_vol()`. <br>
Everything worked fine yesterday and since there was a new commit pushed just 2 hours ago I suspect something went wrong.

**To Reproduce**
1. Install mlfinlab in Google Colab using: `!pip install mlfinlab`
2. Import any function, e.g: `from mlfinlab.datasets import load_tick_sample`
3. Check the type of the returned object: `type( load_tick_sample() )`
4. This returns NoneType

**System**
Only tested in Google Colab.

**EDIT:**
- Inspecting the source code shows that the functions now just pass instead of doing any logic.
- Installing a previous version using `!pip install 'mlfinlab<0.15.1` is a temporary work around.

**Comment by PanPip** [comment]
Hi @tobemo. Thank you for reporting this issue!

This was a mistake on our side, as we've released a version from the public repo into the PyPi.

The MlFinLab v 0.15.2 fixes this. Sorry for the inconvenience.
