### ISSUE TITLE
Looking for guidance / course

### ISSUE THREAD

**Issue by DaveBGld** [hudson-and-thames/mlfinlab#478]
After looking at your library, I bought the two books by Professor Lopez del Prado, but find the material difficult. 

Is there a course that I can take to  understand how to better use your library?

Many thanks!

**Comment by wenmin-wu** [comment]
Hi @DaveBGld, you need to pay $100/month for the notebooks tutorial https://www.patreon.com/HudsonThames.

Even though this project is awesome, but I cannot afford $100/month for the notebooks tutorial, so I'm giving up this library and planning to develop one by myself.

**Comment by Jackal08** [comment]
Hi @DaveBGld, 

Thanks for raising this. We don't have a course at the moment but the notebooks, documentation, source code, and original papers have all the characteristics you need for learning material. 

The only thing missing is video instruction. We don't have immediate plans to offer this but perhaps it's something worth exploring in the future.

You can follow us on Youtube: https://www.youtube.com/channel/UC8hI87gt0dmTAIEupEcsckA

Best regards
Jacques Joubert
