### ISSUE TITLE
Is $100/month for notebooks tutorial too expensive?

### ISSUE THREAD

**Issue by wenmin-wu** [hudson-and-thames/mlfinlab#482]
Hi, I should say this library is incredible, but to better understand your library I need to pay $100/month for the notebooks tutorial. I cannot afford such an expensive subscription fee.

**Comment by Jackal08** [comment]
Hi @wenmin-wu, 

Thank you for your interest in the library. We have decided to let MlFinLab be have a strong community edition for free and then pair that with paid documentation. The alternative would be to have docs for free but the code base behind a paywall. 

I believe that you already have everything you need to make a success of learning about ML in Finance. We highly recommend Advances in Financial Machine Learning. Our notebooks are supplementary to that.  

Best regards
Jacques Joubert

**Comment by wenmin-wu** [comment]
haha, thanks for opening the code base, I can understand the usage of this tool by going through the source code. One question, how frequently will the notebooks be updated? If it's not frequent, then maybe I can subscribe for one month to go through all the notebooks and then cancel it.
