### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by dlarsen5** [hudson-and-thames/mlfinlab#486]
Adding these as a feature ticket since I'm not sure what these would affect what's planned for development

1. Remove Tensorflow as a dependency
- Tensorflow isn't used in the repo yet is listed as a requirement (bloats basic install)
2. Two different sources of dependency version
- setup.py includes specific dependency versions vs. listing them in requirements.txt
3. Add cxvpy to requirements
- used in mlfinlab.portfolio_optimization

**Comment by Jackal08** [comment]
Thanks @dlarsen5. 

I will be moving this thread over to #487 

1. We will be dropping TF. Thank you
2. The setup.py and req.txt files are doing for two separate processes. The req.txt is for the developers and the build server where setup.py is for PyPi and installs. 
3. All the portfolio optimization modules now live in PortfolioLab and have been deprecated from MlFinLab. So no need for cvxpy.

**Comment by PanPip** [comment]
@dlarsen5 Thank you for adding this ticket!

As @Jackal08 said, we've dropped the TensorFlow dependency in the newly released v1.0.1.
