### ISSUE TITLE
basic functions from standard_data_structures return index 2 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by N4D1K-lgtm** [hudson-and-thames/mlfinlab#489]
I am attempting to transform .csv/pandas data frame file generated by load_tick_sample() to volume/time/dollar bars.

```
from mlfinlab.datasets import (load_tick_sample, load_stock_prices, load_dollar_bar_sample)
from mlfinlab.data_structures import standard_data_structures

tick_df = load_tick_sample()
volume = standard_data_structures.get_volume_bars(tick_df, threshold=5500, batch_size=1000000, verbose=False)
```

**Expected behavior**
return pandas dataframe aggregated by the unit declared in the function. When loading data from saved CSV file the program compiles but volume is not recognized as a dataframe and returns nothing.

**Output**
`
  File "/home/kali/anaconda3/envs/exnihilo/lib/python3.8/site-packages/mlfinlab/data_structures/standard_data_structures.py", line 79, in _extract_bars
    volume = row[2]
IndexError: index 2 is out of bounds for axis 0 with size 2
 `

**System**
 - Windows 10 Pro and Kali Linux

**Things I tried**
- reinstalling pip, mlfinlab, anaconda, MS build tools, wheel, setuptools
- changing OS (was reproducible on most recent version of Kali Linux)
- changing python versions (3.6, 3.7, 3.8)
- fresh anaconda environment
- renaming columns in csv file to date_time, price, volume
- using my own data sets in date_time, price, volume

I can answer with more information if you need it.

**Comment by proskurin** [comment]
Hi, @N4D1K-lgtm.
Thank you very much for using mlfinlab. 
`When loading data from saved CSV file the program compiles but volume is not recognized as a dataframe and returns nothing.`
Probably there is a problem with delimiter in your csv file in volume column?

**Comment by N4D1K-lgtm** [comment]
> Hi, @N4D1K-lgtm.
> Thank you very much for using mlfinlab. 
> `When loading data from saved CSV file the program compiles but volume is not recognized as a dataframe and returns nothing.`
> Probably there is a problem with delimiter in your csv file in volume column?

The main problem occurs even when I load a data frame from mlfinlabs datasets, not just when reading off of a csv. I ended up writing my own solution so I haven't checked the original issue in a few weeks.

I will look at it when I get home and close the issue if it's resolved.
