### ISSUE TITLE
PurgedKFold class error (purge not working for splits)

### ISSUE THREAD

**Issue by davilramos** [hudson-and-thames/mlfinlab#494]
The function split on the crossvalidation.py (PurgKFold class) is not returning the right splits. The problem is on the following line:
  **test_times = pd.Series(index=[self.samples_info_sets[start_ix]], data=[self.samples_info_sets[end_ix-1]])**.

 Here, the test split used to define the train split is defined from the start to the end of the label date (2nd colloum of the samples_info_sets), where it should start on the first trading date and end on the last label date. One can fix this by replace the line above for :
**test_times = pd.Series(index=[self.samples_info_sets.index[start_ix+1]], data=[self.samples_info_sets[end_ix-1]])**

**Comment by wissam124** [comment]
Hi,

Why was this closed? I think the problem raised here is still an issue (see issue #295 ).
