### ISSUE TITLE
mlfinlab on colab

### ISSUE THREAD

**Issue by cl7805** [hudson-and-thames/mlfinlab#495]
Hi,

I have checked the mlfinlab installation for colab. I have uninstalled tensorflow and upgraded my numpy to 1.20.1. However, the following occurs:
Could not find a version that satisfies the requirement mlfinlab (from versions: )
No matching distribution found for mlfinlab

Can you please help?

**Comment by Jackal08** [comment]
Hi @cl7805, 

Are you using python 3.8?

**Comment by cl7805** [comment]
Hi Jackal08,

I'm struggling to update colab python to 3.8. pip is designed to upgrade python packages and not to upgrade python itself. pip shouldn't try to upgrade python when you ask it to do so. Don't type pip install python but use an installer instead. Basically, pip comes with python itself.

https://stackoverflow.com/questions/16769109/upgade-python-version-using-pip#:~:text=pip%20is%20designed%20to%20upgrade,but%20use%20an%20installer%20instead.&text=Basically%2C%20pip%20comes%20with%20python%20itself.

https://stackoverflow.com/questions/60775160/install-python-3-8-kernel-in-google-colaboratory

None of the proposed solutions work.

**Comment by cl7805** [comment]
https://kegui.medium.com/how-to-install-mlfinlab-without-error-messages-896e2fb43c2f

Neither does this one.

**Comment by Jackal08** [comment]
Hi @cl7805, 

Without Python 3.8, you won't be able to install the library as it only works on that version. I don't know Colab well enough but there must be a way to select a python version.

**Comment by lymadvisors** [comment]
I created an environment with Python 3.8, i was able to install mlfinlab, portffoliolab, but not arbitragelab
this appeared

"ERROR: Could not find a version that satisfies the requirement arbitragelab
ERROR: No matching distribution found for arbitragelab

how could i fix it?

**Comment by lymadvisors** [comment]
I created an environment with Python 3.8, i was able to install mlfinlab, portffoliolab, but not arbitragelab
this appeared

"ERROR: Could not find a version that satisfies the requirement arbitragelab
ERROR: No matching distribution found for arbitragelab

how could i fix it?

**Comment by Jackal08** [comment]
We have added 3.6, 3.7 python compatibility so it now runs on Colab.

**Comment by trevor-richardson** [comment]
I have python  3.8.12 and when I run pip install mlfinlab

ERROR: Could not find a version that satisfies the requirement mlfinlab (from versions: none)
ERROR: No matching distribution found for mlfinlab

**Comment by Jackal08** [comment]
Hi @trevor-richardson, 

MlFinLab is only available to clients. Can be purchased directly from the website: http://hudsonthames.org/mlfinlab

Best regards
