### ISSUE TITLE
ARBITRAGELAB not installing

### ISSUE THREAD

**Issue by lymadvisors** [hudson-and-thames/mlfinlab#498]
**Describe the bug**
PROBLEMS INSTALL ARBITRAGELAB

I created an environment with Python 3.8, i was able to install mlfinlab, portffoliolab, but not arbitragelab
this appeared

"ERROR: Could not find a version that satisfies the requirement arbitragelab
ERROR: No matching distribution found for arbitragelab

how could i fix it?

**Comment by Jackal08** [comment]
Hi @lymadvisors, 

Nice to meet you. 

That's because ArbitrageLab is a paid-for library only available to clients. More can be read about it on the company website: https://hudsonthames.org/arbitragelab/
