### ISSUE TITLE
Any idea of adding code of bull bear labeling?

### ISSUE THREAD

**Issue by leolle** [hudson-and-thames/mlfinlab#518]
Hi, do you have plans to add code of these functions?

**Comment by Jackal08** [comment]
Hi @leolle, 

This implementation is available via subscription. This is just a shell repo. There isn't any code in in.

**Comment by Jackal08** [comment]
Users simply buy a SAAS subscription to mlfinlab from the website: https://hudsonthames.org/mlfinlab/

Its self serve.
