### ISSUE TITLE
get_events should return target * take_profit multiplier

### ISSUE THREAD

**Issue by proskurin** [hudson-and-thames/mlfinlab#53]
In current get_events implementation data frame with side, t1, target is returned. However, target corresponds to volatility level, not the real target return which is volatility * take_profit multiplier.

**Comment by proskurin** [comment]
This issue becomes a bug when we try to use get_bins function call, because in this case, trgt column is used to determine whether fix/profit was hit, however trgt column value always corresponds to fix profit = 1

**Comment by Jackal08** [comment]
This bug has since been corrected in PR #126
