### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by HCMcapital** [hudson-and-thames/mlfinlab#540]

**Comment by rspadim** [comment]
@HCMcapital This one is off, the git is internal now.

**Comment by HCMcapital** [comment]
Sorry, what do you mean? Is there a link to the internal git you referred to? I just want to get access to the documentation again.

**Comment by rspadim** [comment]
The git of mlfinlab is private, maybe paying you have access to it (i'm not sure if the project still alive), it's not opensource anymore

last commit here (github) is 3 years old at master branch: [PanPip](https://github.com/hudson-and-thames/mlfinlab/commits?author=PanPip)
PanPip
[Merge pull request](https://github.com/hudson-and-thames/mlfinlab/commit/79dcc7120ec84110578f75b025a75850eb72fc73) https://github.com/hudson-and-thames/mlfinlab/pull/511 [from hudson-and-thames/readme_update](https://github.com/hudson-and-thames/mlfinlab/commit/79dcc7120ec84110578f75b025a75850eb72fc73)
[79dcc71](https://github.com/hudson-and-thames/mlfinlab/commit/79dcc7120ec84110578f75b025a75850eb72fc73)
 · 
3 years ago

**Comment by HCMcapital** [comment]
Yes, i know. I am a paying subscriber but the website is now broken or not maintained, and the documentation is not accessible. I am wondering if anyone else has had issues or been able to reach someone at H&T for more info?
