### ISSUE TITLE
Is asserting column datatypes really needed?

### ISSUE THREAD

**Issue by atokuz** [hudson-and-thames/mlfinlab#66]
There some data providers which publish volumes in floating point values (for example in millions).
And some assets can be priced only in integer values. Are these assertions required for any calculations of mlfinlab?

**Comment by Jackal08** [comment]
We can remove this assertion but will need to add unit tests to check for fractional units. 

I like the idea and we should do this.

**Comment by Jackal08** [comment]
Hi @atokuz, 

Thanks for your patience. I have just removed the assertion that volume must be an int. I have also updated the PyPi package so that other users will be able to use data from crypto and FX.

Best regards
Jacques Joubert
