### ISSUE TITLE
`add_vertical_barrier` does not handle business day

### ISSUE THREAD

**Issue by lunluen** [hudson-and-thames/mlfinlab#87]
**Describe the bug**
I'm not sure if issue #54 is for this.
`add_vertical_barrier` does not handle business day.
If time delta is `num_days=1`, then `get_events` tends to label events on Fridays as 0,
because `searchsorted` will return the index of the first bar next Monday.

I think using `pd.tseries.offsets.BusinessDay` can solve this according to [Python | Pandas tseries.offsets.BusinessDay](https://www.geeksforgeeks.org/python-pandas-tseries-offsets-businessday/)

**To Reproduce**
```Shell
>>> t_events
DatetimeIndex(['2015-01-30 20:43:58.140000'], dtype='datetime64[ns]', freq=None)
>>> add_vertical_barrier(t_events, close, num_days=1)
2015-01-30 20:43:58.140   2015-02-01 23:26:29.558
Name: date_time, dtype: datetime64[ns]
>>> close.index[1102]
Timestamp('2015-02-01 23:26:29.558000')
>>> close.index[1153]
Timestamp('2015-02-02 20:44:59.143000')
```

**Expected behavior**
`add_vertical_barrier` should return (approximate)
```
2015-01-30 20:43:58.140   2015-02-02 20:44:59.143
Name: date_time, dtype: datetime64[ns]
```
rather than
```
2015-01-30 20:43:58.140   2015-02-01 23:26:29.558
Name: date_time, dtype: datetime64[ns]
```
Otherwise, there would be lots of unexpected 0 labels, and a algorithm would not trade on Fridays.

**Comment by Jackal08** [comment]
Hi @lunluen, Thanks for bringing this to our attention. I will be sure to raise it in our next stand up. 

@proskurin Lets discuss this when we catch up tomorrow.

**Comment by rspadim** [comment]
uhm, maybe the business day should be associated with each "symbol" or market

for example here in Brazil we have a business day and at another country (USA) trading the same asset (Apple for example) don't

**Comment by proskurin** [comment]
Hi @lunluen , @DiePharisaer 
Thank you for your attention and contribution to mlfinlab! As you can see from discussion, various assets have different trading days/hours. It will be rather difficult to create a generic vertical barrier function for cryptos, fx, futures, stocks, etc.
However,the output of add_vertical_barrier is Pandas series with index being events index and values being vertical barriers of events. You can construct them manually depending on asset class you are using.
