### ISSUE TITLE
What is the diff between get avg uniqueness and tipple barrier uniqueness?

### ISSUE THREAD

**Issue by Jackal08** [hudson-and-thames/mlfinlab#90]

**Comment by proskurin** [comment]
The answer is hidden in difference between get_ind_matrix and get_num_conc_events function. The first one is forward-looking it estimates which indices in the future are used to get label value i. Num_conc_events in backward-looking: it estimates how often the index was used to label other labels. However, both functions yield more or less the same values (al least what I've seen by now)

**Comment by Jackal08** [comment]
Thanks for answering! Closing the ticket.
