### ISSUE TITLE
Implementation of `getIndMatrix` is different from the book

### ISSUE THREAD

**Issue by lunluen** [hudson-and-thames/mlfinlab#93]
Sorry I was wrong so I close this.

**Describe the bug**
Current implementation calculates bar_index using
```Python
    bar_index = list(triple_barrier_events.index)  # generate index for indicator matrix from t1 and index
    bar_index.extend(triple_barrier_events.t1)
    bar_index = sorted(list(set(bar_index)))  # drop duplicates and sort
```
So the information about the time span length is gone, and the lengths of all label spans are always 2.

**To Reproduce**
```Python
>>> from mlfinlab.sampling.bootstrapping import get_ind_matrix
>>> ind_mat = get_ind_matrix(triple_barrier_events)
>>> np.all(ind_mat.sum(axis=0) == 2)
True
```

**Expected behavior**
Return `False`.
Like bottom of afml page 65, some columns may have more than two 1s.

**Comment by Jackal08** [comment]
@lunluen I see you reopened this ticket. Would you like us to test this to make sure it works?

**Comment by lunluen** [comment]
Sorry the about reproduction was wrong and I can not edit it.

Let's assume two labels L1, L2
- L1 spans from t1, t2, t3, t4
- L2 spans from t2, t3, t4, t5

Both of their average uniquenesses should be (1 + 0.5*3) / 4 = 5/8
And the indicator matrix should be
```Shell
array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.]])
```
But `get_ind_matrix` will return
```Shell
array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 1.]])
```
because price series is not involved in `get_ind_matrix `.

**Comment by lunluen** [comment]
Every two labels that overlap will give the same results,
e.g., 
```Shell
>>> triple_barrier_events
	                      t1	            trgt
2015-01-08 01:48:57.964	2015-01-08 18:11:19.540	0.008677
2015-01-08 15:00:21.581	2015-01-09 15:02:59.709	0.008060
>>> ind_mat = get_ind_matrix(triple_barrier_events)
>>> ind_mat
array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 1.]])
```

**Comment by proskurin** [comment]
Yes, price series is not included in get_ind_matrix function and Marcos doesn't say whether we should include it in bar_index

**Comment by proskurin** [comment]
In your last example the results are right:
Label 1 uses 2015-01-08 01:48:57.96, but Label 2 - doesn't [1, 0]
Label 1 uses 2015-01-08 15:00:21.581, and label 2 also [1, 1]
Label 1 uses 2015-01-08 18:11:19.540 so does Label 2 [1, 1]
Label doesn't use 2015-01-09 15:02:59.709	0.008060, but Label 2 - does [0, 1]

**Comment by Jackal08** [comment]
@lunluen thanks for bringing this up. We are going to add a unit test to confirm that the books output matches our function.

Will revert when we have some more answers.

**Comment by lunluen** [comment]
@proskurin The results are not so representative.

For these two cases:

Case 1:
- label 1 spans t1, t2, t3, ..., t999
- label 2 spans t2, t3, t4, ..., t1000

By intuition their uniquenesses are ~0.5.

Case 2:

label 1 spans from t1, t2, t3, ..., t999
label 2 spans from t998, t999, t1000, ..., t1997

Again by intuition, their uniquenesses should be ~1.

But currently both are (1+0.5*2)/3 = 2/3

**Comment by proskurin** [comment]
@lunluen, I see you point and agree with that. The problem is how we form bar index, not indicator matrix computation (we have created unit tests which check results for the book and our implementation and results are the same). I agree that bars data should included in forming bar index in indicator matrix, not just triple-barrier events

**Comment by proskurin** [comment]
@lunluen we have updated get_ind_matrix function implementation so that bars index is taken into account. Could you please look at it and say if we are on the same page?
Thank you

**Comment by lunluen** [comment]
@proskurin Yes, exactly the same. Thx!
