### ISSUE TITLE
Cannot converge while merging tick imbalance bars

### ISSUE THREAD

**Issue by yuchengwto** [hudson-and-thames/mlfinlab#98]
Guys, have u ever met this problem?
`In [26]: res = mlfinlab.data_structures.get_tick_imbalance_bars(path_, 50, 1000)`
`In [27]: res
Out[27]:
                            date_time          open  ...         close       volume
0       2019-07-07 01:01:32.652000000  11276.000000  ...  11210.000000   395.311349
1       2019-07-07 02:51:57.741000000  11210.000000  ...  11130.000000   577.519686
2       2019-07-07 06:38:15.639000000  11130.000000  ...  11203.000000  1096.206388
3       2019-07-07 11:29:44.698000000  11203.000000  ...  11361.000000   980.128337
4       2019-07-07 11:29:46.009000000  11361.000000  ...  11366.000000    13.877771
5       2019-07-07 11:29:46.213000000  11366.000000  ...  11366.000000     0.301300
6       2019-07-07 11:30:11.551000000  11366.000000  ...  11368.000000    23.228099
7       2019-07-07 11:30:43.179000000  11368.000000  ...  11336.000000     5.960929
8       2019-07-07 11:30:54.108000000  11336.000000  ...  11354.000000     3.368090
9       2019-07-07 11:31:01.005000000  11354.000000  ...  11360.000000     1.201738
10      2019-07-07 11:31:41.411000000  11360.000000  ...  11363.000000     5.781358
11      2019-07-07 11:31:59.655000000  11363.000000  ...  11359.000000     0.463053
12      2019-07-07 11:32:01.518000000  11359.000000  ...  11355.000000     0.844763
13      2019-07-07 11:32:15.132000000  11355.000000  ...  11359.000000     0.078297
14      2019-07-07 11:32:24.891000000  11359.000000  ...  11350.000000     0.439543
15      2019-07-07 11:32:24.891000000  11350.000000  ...  11349.278360     0.855000
16      2019-07-07 11:32:32.321000000  11349.278360  ...  11349.000000     0.024400
17      2019-07-07 11:32:38.925000000  11349.000000  ...  11349.307177     0.005000
18      2019-07-07 11:32:42.225000000  11349.307177  ...  11350.000000     0.020000
19      2019-07-07 11:32:44.915000000  11350.000000  ...  11348.000000     0.005000
20      2019-07-07 11:32:50.130000000  11348.000000  ...  11348.000000     0.025000
21      2019-07-07 11:32:50.345000000  11348.000000  ...  11348.000000     0.000500
22      2019-07-07 11:32:51.960000000  11348.000000  ...  11349.000000     0.020000
23      2019-07-07 11:32:52.813000000  11349.000000  ...  11348.000000     0.106642
24      2019-07-07 11:32:52.885000000  11348.000000  ...  11348.000000     0.362858
25      2019-07-07 11:32:54.936000000  11348.000000  ...  11344.000000     0.020000
26      2019-07-07 11:33:00.869000000  11344.000000  ...  11337.292932     0.008530
27      2019-07-07 11:33:00.869000000  11337.292932  ...  11337.000000     0.003470
28      2019-07-07 11:33:00.869000000  11337.000000  ...  11343.000000     0.008000
29      2019-07-07 11:33:02.263000000  11343.000000  ...  11344.000000     0.200201
...                               ...           ...  ...           ...          ...
829621  2019-07-17 00:05:59.775000000   9479.900000  ...   9479.900000     0.005000
829622  2019-07-17 00:06:02.233000000   9479.900000  ...   9479.926203     0.005000
829623  2019-07-17 00:06:03.775000000   9479.926203  ...   9477.600000     0.054919
829624  2019-07-17 00:06:03.775000000   9477.600000  ...   9472.200000     0.100081
829625  2019-07-17 00:06:03.775000000   9472.200000  ...   9479.900000     0.475000
829626  2019-07-17 00:06:04.667000000   9479.900000  ...   9473.800000     0.052570
829627  2019-07-17 00:06:08.959000000   9473.800000  ...   9472.463345     0.005000
829628  2019-07-17 00:06:12.489000000   9472.463345  ...   9472.458424     0.007000
829629  2019-07-17 00:06:12.746000000   9472.458424  ...   9471.600000     0.003000
829630  2019-07-17 00:06:12.985000000   9471.600000  ...   9473.200000     0.003000
829631  2019-07-17 00:06:13.451000000   9473.200000  ...   9473.200000     0.005000
829632  2019-07-17 00:06:17.196000000   9473.200000  ...   9478.926158     0.007364
829633  2019-07-17 00:06:17.196000000   9478.926158  ...   9473.312484     0.002636
829634  2019-07-17 00:06:19.833000000   9473.312484  ...   9479.700000     0.025000
829635  2019-07-17 00:06:23.619000000   9479.700000  ...   9472.800000     0.050000
829636  2019-07-17 00:06:24.166000000   9472.800000  ...   9471.800000     0.020590
829637  2019-07-17 00:06:26.738000000   9471.800000  ...   9470.800000     0.005000
829638  2019-07-17 00:06:29.878000000   9470.800000  ...   9478.900000     0.737578
829639  2019-07-17 00:06:29.878000000   9478.900000  ...   9478.800000     1.388973
829640  2019-07-17 00:06:29.878000000   9478.800000  ...   9478.600000     0.174806
829641  2019-07-17 00:06:29.878000000   9478.600000  ...   9480.100000     0.432925
829642  2019-07-17 00:06:29.878000000   9480.100000  ...   9478.700000     0.500000
829643  2019-07-17 00:06:29.878000000   9478.700000  ...   9478.500000     0.100000
829644  2019-07-17 00:06:29.878000000   9478.500000  ...   9478.500000     0.200000
829645  2019-07-17 00:06:29.878000000   9478.500000  ...   9481.000000     0.500000
829646  2019-07-17 00:06:29.878000000   9481.000000  ...   9481.600000     0.247993
829647  2019-07-17 00:06:29.878000000   9481.600000  ...   9476.400000     0.357412
829648  2019-07-17 00:06:29.878000000   9476.400000  ...   9476.154272     0.002901
829649  2019-07-17 00:06:29.878000000   9476.154272  ...   9473.700000     0.357412
829650  2019-07-17 00:06:33.698000000   9473.700000  ...   9476.400000     0.010000

[829651 rows x 6 columns]`

the volume of merged tick bars will diverge to a tiny value after several bars with the third parameter that is "exp_num_ticks_init" set to a relatively small value like 1000.

How can i avoid this divergence happens ? 
Plz give me some help.

**Comment by proskurin** [comment]
Hey, @yuchengwto . This a problem with imbalance bars because they are highly dependent on parameters which are used to generate that. Please refer to notebook:
[https://github.com/hudson-and-thames/research/blob/master/Chapter2/2019-04-11_OP_Dollar-Imbalance-Bars.ipynb](url)

**Comment by Jackal08** [comment]
Link fixed: [Imbalance Bars](https://github.com/hudson-and-thames/research/blob/master/Chapter2/2019-04-11_OP_Dollar-Imbalance-Bars.ipynb)

**Comment by yuchengwto** [comment]
@proskurin Thank you very much. 
So when the initial ticks are set small, the divergence to near zeros always happens and inevitable?

**Comment by proskurin** [comment]
It depends on data, but usually low values of initial_ticks and high values of num_bars make bars converge to ticks
